import type { PracticumMaterial, MaterialRequest } from "./types"

export const mockPracticumMaterials: PracticumMaterial[] = [
  {
    id: "material-1",
    name: "Network Cable Crimping Tools",
    category: "Tools",
    course: "Computer Networks Laboratory",
    quantity: 15,
    unit: "sets",
    threshold: 5,
    description: "Tools for crimping RJ45 connectors to network cables",
    createdAt: "2023-08-01T08:00:00Z",
    updatedAt: "2023-09-15T14:30:00Z",
  },
  {
    id: "material-2",
    name: "Ethernet Cables",
    category: "Hardware",
    course: "Computer Networks Laboratory",
    quantity: 50,
    unit: "m",
    threshold: 10,
    description: "Cat6 Ethernet cables for network practicum",
    createdAt: "2023-08-01T08:15:00Z",
    updatedAt: "2023-09-20T10:45:00Z",
  },
  {
    id: "material-3",
    name: "Network Analyzer Software",
    category: "Software",
    course: "Computer Networks Laboratory",
    quantity: 25,
    unit: "licenses",
    threshold: 5,
    description: "Software for analyzing network traffic and protocols",
    createdAt: "2023-08-02T09:30:00Z",
    updatedAt: "2023-08-02T09:30:00Z",
  },
  {
    id: "material-4",
    name: "Database Management Software",
    category: "Software",
    course: "Database Systems Laboratory",
    quantity: 30,
    unit: "licenses",
    threshold: 5,
    description: "DBMS software for database practicum",
    createdAt: "2023-08-03T10:45:00Z",
    updatedAt: "2023-08-03T10:45:00Z",
  },
  {
    id: "material-5",
    name: "SQL Client Tools",
    category: "Software",
    course: "Database Systems Laboratory",
    quantity: 30,
    unit: "licenses",
    threshold: 5,
    description: "SQL client tools for database practicum",
    createdAt: "2023-08-03T11:00:00Z",
    updatedAt: "2023-08-03T11:00:00Z",
  },
  {
    id: "material-6",
    name: "Virtual Machine Software",
    category: "Software",
    course: "Operating Systems Laboratory",
    quantity: 25,
    unit: "licenses",
    threshold: 5,
    description: "Virtualization software for OS practicum",
    createdAt: "2023-08-04T13:15:00Z",
    updatedAt: "2023-08-04T13:15:00Z",
  },
  {
    id: "material-7",
    name: "Linux Distribution ISO",
    category: "Software",
    course: "Operating Systems Laboratory",
    quantity: 10,
    unit: "copies",
    threshold: 3,
    description: "Linux distribution ISO images for OS practicum",
    createdAt: "2023-08-04T13:30:00Z",
    updatedAt: "2023-09-10T09:20:00Z",
  },
  {
    id: "material-8",
    name: "C Programming Environment",
    category: "Software",
    course: "Operating Systems Laboratory",
    quantity: 25,
    unit: "licenses",
    threshold: 5,
    description: "C programming environment for OS practicum",
    createdAt: "2023-08-04T13:45:00Z",
    updatedAt: "2023-08-04T13:45:00Z",
  },
  {
    id: "material-9",
    name: "Digital Electronics Kit",
    category: "Electronics",
    course: "Digital Electronics Laboratory",
    quantity: 15,
    unit: "sets",
    threshold: 3,
    description: "Digital electronics kits for practicum",
    createdAt: "2023-08-05T09:00:00Z",
    updatedAt: "2023-09-18T11:30:00Z",
  },
  {
    id: "material-10",
    name: "Breadboard",
    category: "Electronics",
    course: "Digital Electronics Laboratory",
    quantity: 20,
    unit: "pcs",
    threshold: 5,
    description: "Breadboards for digital electronics practicum",
    createdAt: "2023-08-05T09:15:00Z",
    updatedAt: "2023-09-18T11:35:00Z",
  },
  {
    id: "material-11",
    name: "Digital Multimeter",
    category: "Tools",
    course: "Digital Electronics Laboratory",
    quantity: 12,
    unit: "pcs",
    threshold: 3,
    description: "Digital multimeters for electronics practicum",
    createdAt: "2023-08-05T09:30:00Z",
    updatedAt: "2023-09-18T11:40:00Z",
  },
  {
    id: "material-12",
    name: "Logic Analyzer",
    category: "Tools",
    course: "Digital Electronics Laboratory",
    quantity: 5,
    unit: "pcs",
    threshold: 2,
    description: "Logic analyzers for digital electronics practicum",
    createdAt: "2023-08-05T09:45:00Z",
    updatedAt: "2023-09-18T11:45:00Z",
  },
  {
    id: "material-13",
    name: "Microprocessor Development Board",
    category: "Electronics",
    course: "Microprocessors Laboratory",
    quantity: 0,
    unit: "pcs",
    threshold: 5,
    description: "Development boards for microprocessor practicum",
    createdAt: "2023-08-06T10:00:00Z",
    updatedAt: "2023-09-25T14:20:00Z",
  },
  {
    id: "material-14",
    name: "Electronic Components Kit",
    category: "Electronics",
    course: "Microprocessors Laboratory",
    quantity: 3,
    unit: "sets",
    threshold: 5,
    description: "Electronic components for microprocessor practicum",
    createdAt: "2023-08-06T10:15:00Z",
    updatedAt: "2023-09-25T14:25:00Z",
  },
  {
    id: "material-15",
    name: "Programming Cable",
    category: "Hardware",
    course: "Microprocessors Laboratory",
    quantity: 8,
    unit: "pcs",
    threshold: 3,
    description: "Programming cables for microprocessor development boards",
    createdAt: "2023-08-06T10:30:00Z",
    updatedAt: "2023-09-25T14:30:00Z",
  },
]

export const mockMaterialRequests: MaterialRequest[] = [
  {
    id: "request-1",
    materialId: "material-1",
    requesterName: "Dr. Budi Santoso",
    requesterRole: "instructor",
    course: "Computer Networks Laboratory",
    quantity: 2,
    requestDate: "2023-09-28T09:15:00Z",
    status: "pending",
    notes: "Needed for next week's practicum session",
  },
  {
    id: "request-2",
    materialId: "material-2",
    requesterName: "Arif Rahman",
    requesterRole: "assistant",
    course: "Computer Networks Laboratory",
    quantity: 10,
    requestDate: "2023-09-27T14:30:00Z",
    status: "approved",
    notes: "For cable crimping demonstration",
    approvedDate: "2023-09-27T16:45:00Z",
  },
  {
    id: "request-3",
    materialId: "material-9",
    requesterName: "Dr. Rina Marlina",
    requesterRole: "instructor",
    course: "Digital Electronics Laboratory",
    quantity: 3,
    requestDate: "2023-09-26T11:20:00Z",
    status: "approved",
    notes: "Replacement for damaged kits",
    approvedDate: "2023-09-26T13:10:00Z",
  },
  {
    id: "request-4",
    materialId: "material-13",
    requesterName: "Dr. Ahmad Firdaus",
    requesterRole: "instructor",
    course: "Microprocessors Laboratory",
    quantity: 5,
    requestDate: "2023-09-25T10:05:00Z",
    status: "rejected",
    notes: "Needed for upcoming semester",
    rejectedDate: "2023-09-25T14:20:00Z",
    rejectionReason: "Out of stock. New order has been placed with the supplier.",
  },
  {
    id: "request-5",
    materialId: "material-7",
    requesterName: "Budi Setiawan",
    requesterRole: "assistant",
    course: "Operating Systems Laboratory",
    quantity: 2,
    requestDate: "2023-09-29T08:45:00Z",
    status: "pending",
    notes: "For student who missed the previous session",
  },
  {
    id: "request-6",
    materialId: "material-11",
    requesterName: "Dr. Budi Hartono",
    requesterRole: "instructor",
    course: "Digital Electronics Laboratory",
    quantity: 1,
    requestDate: "2023-09-29T09:30:00Z",
    status: "pending",
    notes: "Replacement for malfunctioning unit",
  },
]

