import type { PracticumCourse, PracticumEnrollment, PracticumSession } from "./types"
import type { PracticumSchedule } from "./types"

// Mock Practicum Enrollments
export const mockPracticumEnrollments: PracticumEnrollment[] = [
  {
    id: "enr-001",
    studentId: "2020-CS-001",
    studentName: "Ahmad Fauzi",
    courseName: "Computer Networks Laboratory",
    courseCode: "CSL-301",
    enrollmentDate: "2023-08-15",
    status: "in_progress",
    labSection: "A",
    scheduleDay: "Monday",
    scheduleTime: "09:00 - 11:00",
    instructor: "Dr. Budi Santoso",
    paymentStatus: "paid",
    paymentAmount: 500000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: true },
      { id: "req-002", name: "Safety Training", completed: true },
      { id: "req-003", name: "Prerequisites", completed: true },
    ],
    attendance: [
      { date: "2023-09-04", status: "present" },
      { date: "2023-09-11", status: "present" },
      { date: "2023-09-18", status: "late", notes: "Arrived 15 minutes late" },
      { date: "2023-09-25", status: "present" },
    ],
    grades: [
      { assignmentName: "Lab 1: Network Configuration", score: 85, maxScore: 100, weight: 0.15, date: "2023-09-11" },
      { assignmentName: "Lab 2: Subnetting", score: 90, maxScore: 100, weight: 0.15, date: "2023-09-18" },
      { assignmentName: "Lab 3: Routing Protocols", score: 78, maxScore: 100, weight: 0.15, date: "2023-09-25" },
    ],
  },
  {
    id: "enr-002",
    studentId: "2020-CS-045",
    studentName: "Siti Rahayu",
    courseName: "Database Systems Laboratory",
    courseCode: "CSL-302",
    enrollmentDate: "2023-08-16",
    status: "in_progress",
    labSection: "B",
    scheduleDay: "Tuesday",
    scheduleTime: "13:00 - 15:00",
    instructor: "Dr. Dewi Anggraini",
    paymentStatus: "paid",
    paymentAmount: 500000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: true },
      { id: "req-002", name: "Software Installation", completed: true },
      { id: "req-003", name: "Prerequisites", completed: true },
    ],
    attendance: [
      { date: "2023-09-05", status: "present" },
      { date: "2023-09-12", status: "present" },
      { date: "2023-09-19", status: "present" },
      { date: "2023-09-26", status: "absent", notes: "Medical leave" },
    ],
    grades: [
      { assignmentName: "Lab 1: SQL Basics", score: 95, maxScore: 100, weight: 0.15, date: "2023-09-12" },
      { assignmentName: "Lab 2: Database Design", score: 88, maxScore: 100, weight: 0.15, date: "2023-09-19" },
      { assignmentName: "Lab 3: Stored Procedures", score: 0, maxScore: 100, weight: 0.15, date: "2023-09-26" },
    ],
  },
  {
    id: "enr-003",
    studentId: "2021-CS-078",
    studentName: "Reza Pratama",
    courseName: "Operating Systems Laboratory",
    courseCode: "CSL-303",
    enrollmentDate: "2023-08-14",
    status: "in_progress",
    labSection: "A",
    scheduleDay: "Wednesday",
    scheduleTime: "10:00 - 12:00",
    instructor: "Dr. Hadi Wijaya",
    paymentStatus: "paid",
    paymentAmount: 500000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: true },
      { id: "req-002", name: "Virtual Machine Setup", completed: true },
      { id: "req-003", name: "Prerequisites", completed: true },
    ],
    attendance: [
      { date: "2023-09-06", status: "present" },
      { date: "2023-09-13", status: "present" },
      { date: "2023-09-20", status: "present" },
      { date: "2023-09-27", status: "present" },
    ],
    grades: [
      { assignmentName: "Lab 1: Process Management", score: 82, maxScore: 100, weight: 0.15, date: "2023-09-13" },
      { assignmentName: "Lab 2: Memory Management", score: 75, maxScore: 100, weight: 0.15, date: "2023-09-20" },
      { assignmentName: "Lab 3: File Systems", score: 90, maxScore: 100, weight: 0.15, date: "2023-09-27" },
    ],
  },
  {
    id: "enr-004",
    studentId: "2021-CS-102",
    studentName: "Anisa Putri",
    courseName: "Computer Networks Laboratory",
    courseCode: "CSL-301",
    enrollmentDate: "2023-08-17",
    status: "pending",
    labSection: "B",
    scheduleDay: "Monday",
    scheduleTime: "13:00 - 15:00",
    instructor: "Dr. Budi Santoso",
    paymentStatus: "unpaid",
    paymentAmount: 500000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: false },
      { id: "req-002", name: "Safety Training", completed: false },
      { id: "req-003", name: "Prerequisites", completed: true },
    ],
    attendance: [],
    grades: [],
  },
  {
    id: "enr-005",
    studentId: "2022-CS-056",
    studentName: "Dimas Ardianto",
    courseName: "Database Systems Laboratory",
    courseCode: "CSL-302",
    enrollmentDate: "2023-08-18",
    status: "approved",
    labSection: "A",
    scheduleDay: "Thursday",
    scheduleTime: "09:00 - 11:00",
    instructor: "Dr. Dewi Anggraini",
    paymentStatus: "partial",
    paymentAmount: 250000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: true },
      { id: "req-002", name: "Software Installation", completed: true },
      { id: "req-003", name: "Prerequisites", completed: true },
    ],
    attendance: [],
    grades: [],
  },
  {
    id: "enr-006",
    studentId: "2022-CS-089",
    studentName: "Maya Indah",
    courseName: "Operating Systems Laboratory",
    courseCode: "CSL-303",
    enrollmentDate: "2023-08-15",
    status: "rejected",
    labSection: "B",
    scheduleDay: "Friday",
    scheduleTime: "13:00 - 15:00",
    instructor: "Dr. Hadi Wijaya",
    notes: "Missing prerequisite courses",
    paymentStatus: "unpaid",
    paymentAmount: 500000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: false },
      { id: "req-002", name: "Virtual Machine Setup", completed: false },
      { id: "req-003", name: "Prerequisites", completed: false },
    ],
    attendance: [],
    grades: [],
  },
  {
    id: "enr-007",
    studentId: "2020-CS-123",
    studentName: "Farhan Rizki",
    courseName: "Digital Electronics Laboratory",
    courseCode: "CSL-304",
    enrollmentDate: "2023-08-16",
    status: "completed",
    labSection: "A",
    scheduleDay: "Tuesday",
    scheduleTime: "10:00 - 12:00",
    instructor: "Dr. Rina Marlina",
    paymentStatus: "paid",
    paymentAmount: 500000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: true },
      { id: "req-002", name: "Component Kit", completed: true },
      { id: "req-003", name: "Prerequisites", completed: true },
    ],
    attendance: [
      { date: "2023-09-05", status: "present" },
      { date: "2023-09-12", status: "present" },
      { date: "2023-09-19", status: "present" },
      { date: "2023-09-26", status: "present" },
    ],
    grades: [
      { assignmentName: "Lab 1: Logic Gates", score: 92, maxScore: 100, weight: 0.15, date: "2023-09-12" },
      { assignmentName: "Lab 2: Flip-Flops", score: 88, maxScore: 100, weight: 0.15, date: "2023-09-19" },
      { assignmentName: "Lab 3: Counters", score: 95, maxScore: 100, weight: 0.15, date: "2023-09-26" },
      { assignmentName: "Final Project", score: 90, maxScore: 100, weight: 0.55, date: "2023-10-03" },
    ],
  },
  {
    id: "enr-008",
    studentId: "2021-CS-145",
    studentName: "Putri Wulandari",
    courseName: "Computer Networks Laboratory",
    courseCode: "CSL-301",
    enrollmentDate: "2023-08-17",
    status: "in_progress",
    labSection: "C",
    scheduleDay: "Wednesday",
    scheduleTime: "13:00 - 15:00",
    instructor: "Dr. Budi Santoso",
    paymentStatus: "paid",
    paymentAmount: 500000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: true },
      { id: "req-002", name: "Safety Training", completed: true },
      { id: "req-003", name: "Prerequisites", completed: true },
    ],
    attendance: [
      { date: "2023-09-06", status: "present" },
      { date: "2023-09-13", status: "late", notes: "Arrived 10 minutes late" },
      { date: "2023-09-20", status: "present" },
      { date: "2023-09-27", status: "present" },
    ],
    grades: [
      { assignmentName: "Lab 1: Network Configuration", score: 80, maxScore: 100, weight: 0.15, date: "2023-09-13" },
      { assignmentName: "Lab 2: Subnetting", score: 85, maxScore: 100, weight: 0.15, date: "2023-09-20" },
      { assignmentName: "Lab 3: Routing Protocols", score: 88, maxScore: 100, weight: 0.15, date: "2023-09-27" },
    ],
  },
  {
    id: "enr-009",
    studentId: "2022-CS-167",
    studentName: "Andi Firmansyah",
    courseName: "Database Systems Laboratory",
    courseCode: "CSL-302",
    enrollmentDate: "2023-08-18",
    status: "pending",
    labSection: "C",
    scheduleDay: "Thursday",
    scheduleTime: "13:00 - 15:00",
    instructor: "Dr. Dewi Anggraini",
    paymentStatus: "unpaid",
    paymentAmount: 500000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: false },
      { id: "req-002", name: "Software Installation", completed: true },
      { id: "req-003", name: "Prerequisites", completed: true },
    ],
    attendance: [],
    grades: [],
  },
  {
    id: "enr-010",
    studentId: "2020-CS-189",
    studentName: "Rina Fitriani",
    courseName: "Operating Systems Laboratory",
    courseCode: "CSL-303",
    enrollmentDate: "2023-08-15",
    status: "in_progress",
    labSection: "C",
    scheduleDay: "Friday",
    scheduleTime: "09:00 - 11:00",
    instructor: "Dr. Hadi Wijaya",
    paymentStatus: "paid",
    paymentAmount: 500000,
    requirements: [
      { id: "req-001", name: "Lab Manual", completed: true },
      { id: "req-002", name: "Virtual Machine Setup", completed: true },
      { id: "req-003", name: "Prerequisites", completed: true },
    ],
    attendance: [
      { date: "2023-09-08", status: "present" },
      { date: "2023-09-15", status: "present" },
      { date: "2023-09-22", status: "absent", notes: "Family emergency" },
      { date: "2023-09-29", status: "present" },
    ],
    grades: [
      { assignmentName: "Lab 1: Process Management", score: 78, maxScore: 100, weight: 0.15, date: "2023-09-15" },
      { assignmentName: "Lab 2: Memory Management", score: 0, maxScore: 100, weight: 0.15, date: "2023-09-22" },
      { assignmentName: "Lab 3: File Systems", score: 85, maxScore: 100, weight: 0.15, date: "2023-09-29" },
    ],
  },
]

// Mock Practicum Courses
export const mockPracticumCourses: PracticumCourse[] = [
  {
    id: "course-001",
    name: "Computer Networks Laboratory",
    code: "CSL-301",
    semester: "Fall",
    academicYear: "2023/2024",
    credits: 2,
    description:
      "Practical implementation of computer networking concepts including configuration, troubleshooting, and analysis of network protocols.",
    maxCapacity: 30,
    currentEnrollment: 25,
    instructors: ["Dr. Budi Santoso", "Dr. Ahmad Firdaus"],
    schedule: [
      { day: "Monday", startTime: "09:00", endTime: "11:00", location: "Lab Room 101" },
      { day: "Monday", startTime: "13:00", endTime: "15:00", location: "Lab Room 101" },
      { day: "Wednesday", startTime: "13:00", endTime: "15:00", location: "Lab Room 101" },
    ],
    prerequisites: ["CS-201: Computer Networks"],
    materials: [
      { name: "Network Cable Crimping Tools", required: true },
      { name: "Ethernet Cables", required: true },
      { name: "Network Analyzer Software", required: true },
    ],
    status: "active",
  },
  {
    id: "course-002",
    name: "Database Systems Laboratory",
    code: "CSL-302",
    semester: "Fall",
    academicYear: "2023/2024",
    credits: 2,
    description:
      "Hands-on experience with database management systems, SQL programming, database design, and implementation of database applications.",
    maxCapacity: 25,
    currentEnrollment: 20,
    instructors: ["Dr. Dewi Anggraini", "Dr. Rini Suryani"],
    schedule: [
      { day: "Tuesday", startTime: "13:00", endTime: "15:00", location: "Lab Room 102" },
      { day: "Thursday", startTime: "09:00", endTime: "11:00", location: "Lab Room 102" },
      { day: "Thursday", startTime: "13:00", endTime: "15:00", location: "Lab Room 102" },
    ],
    prerequisites: ["CS-202: Database Systems"],
    materials: [
      { name: "Database Management Software", required: true },
      { name: "SQL Client Tools", required: true },
    ],
    status: "active",
  },
  {
    id: "course-003",
    name: "Operating Systems Laboratory",
    code: "CSL-303",
    semester: "Fall",
    academicYear: "2023/2024",
    credits: 2,
    description:
      "Practical implementation of operating system concepts including process management, memory management, file systems, and system programming.",
    maxCapacity: 25,
    currentEnrollment: 18,
    instructors: ["Dr. Hadi Wijaya", "Dr. Siti Aminah"],
    schedule: [
      { day: "Wednesday", startTime: "10:00", endTime: "12:00", location: "Lab Room 103" },
      { day: "Friday", startTime: "09:00", endTime: "11:00", location: "Lab Room 103" },
      { day: "Friday", startTime: "13:00", endTime: "15:00", location: "Lab Room 103" },
    ],
    prerequisites: ["CS-203: Operating Systems"],
    materials: [
      { name: "Virtual Machine Software", required: true },
      { name: "Linux Distribution ISO", required: true },
      { name: "C Programming Environment", required: true },
    ],
    status: "active",
  },
  {
    id: "course-004",
    name: "Digital Electronics Laboratory",
    code: "CSL-304",
    semester: "Fall",
    academicYear: "2023/2024",
    credits: 2,
    description:
      "Hands-on experience with digital circuits, logic gates, flip-flops, counters, and digital system design.",
    maxCapacity: 20,
    currentEnrollment: 15,
    instructors: ["Dr. Rina Marlina", "Dr. Budi Hartono"],
    schedule: [{ day: "Tuesday", startTime: "10:00", endTime: "12:00", location: "Lab Room 104" }],
    prerequisites: ["CS-204: Digital Electronics"],
    materials: [
      { name: "Digital Electronics Kit", required: true },
      { name: "Breadboard", required: true },
      { name: "Digital Multimeter", required: true },
      { name: "Logic Analyzer", required: false },
    ],
    status: "active",
  },
  {
    id: "course-005",
    name: "Microprocessors Laboratory",
    code: "CSL-305",
    semester: "Spring",
    academicYear: "2023/2024",
    credits: 2,
    description: "Practical implementation of microprocessor programming, interfacing, and applications.",
    maxCapacity: 20,
    currentEnrollment: 0,
    instructors: ["Dr. Ahmad Firdaus", "Dr. Rina Marlina"],
    schedule: [{ day: "Monday", startTime: "10:00", endTime: "12:00", location: "Lab Room 105" }],
    prerequisites: ["CS-205: Microprocessors"],
    materials: [
      { name: "Microprocessor Development Board", required: true },
      { name: "Electronic Components Kit", required: true },
      { name: "Programming Cable", required: true },
    ],
    status: "upcoming",
  },
]

// Mock Practicum Sessions
export const mockPracticumSessions: PracticumSession[] = [
  {
    id: "session-001",
    courseId: "course-001",
    courseName: "Computer Networks Laboratory",
    date: "2023-09-04",
    startTime: "09:00",
    endTime: "11:00",
    location: "Lab Room 101",
    instructor: "Dr. Budi Santoso",
    assistants: ["Arif Rahman", "Dina Putri"],
    topic: "Network Configuration Basics",
    materials: ["Ethernet cables", "Routers", "Switches"],
    status: "completed",
    attendanceCount: 10,
    totalEnrolled: 10,
    notes: "All students completed the lab successfully",
  },
  {
    id: "session-002",
    courseId: "course-001",
    courseName: "Computer Networks Laboratory",
    date: "2023-09-11",
    startTime: "09:00",
    endTime: "11:00",
    location: "Lab Room 101",
    instructor: "Dr. Budi Santoso",
    assistants: ["Arif Rahman", "Dina Putri"],
    topic: "Subnetting",
    materials: ["Subnet calculators", "Network diagrams"],
    status: "completed",
    attendanceCount: 9,
    totalEnrolled: 10,
    notes: "One student was absent due to illness",
  },
  {
    id: "session-003",
    courseId: "course-001",
    courseName: "Computer Networks Laboratory",
    date: "2023-09-18",
    startTime: "09:00",
    endTime: "11:00",
    location: "Lab Room 101",
    instructor: "Dr. Budi Santoso",
    assistants: ["Arif Rahman", "Dina Putri"],
    topic: "Routing Protocols",
    materials: ["Routers", "Network cables", "Protocol documentation"],
    status: "completed",
    attendanceCount: 10,
    totalEnrolled: 10,
    notes: "Two students had difficulty with RIP configuration",
  },
  {
    id: "session-004",
    courseId: "course-001",
    courseName: "Computer Networks Laboratory",
    date: "2023-09-25",
    startTime: "09:00",
    endTime: "11:00",
    location: "Lab Room 101",
    instructor: "Dr. Budi Santoso",
    assistants: ["Arif Rahman", "Dina Putri"],
    topic: "Network Security",
    materials: ["Firewalls", "Security software"],
    status: "completed",
    attendanceCount: 10,
    totalEnrolled: 10,
  },
  {
    id: "session-005",
    courseId: "course-001",
    courseName: "Computer Networks Laboratory",
    date: "2023-10-02",
    startTime: "09:00",
    endTime: "11:00",
    location: "Lab Room 101",
    instructor: "Dr. Budi Santoso",
    assistants: ["Arif Rahman", "Dina Putri"],
    topic: "Wireless Networks",
    materials: ["Wireless routers", "Access points"],
    status: "scheduled",
    attendanceCount: 0,
    totalEnrolled: 10,
  },
  {
    id: "session-006",
    courseId: "course-002",
    courseName: "Database Systems Laboratory",
    date: "2023-09-05",
    startTime: "13:00",
    endTime: "15:00",
    location: "Lab Room 102",
    instructor: "Dr. Dewi Anggraini",
    assistants: ["Budi Setiawan", "Rina Fitriani"],
    topic: "SQL Basics",
    materials: ["SQL Server", "Sample databases"],
    status: "completed",
    attendanceCount: 8,
    totalEnrolled: 8,
    notes: "All students completed the basic queries",
  },
  {
    id: "session-007",
    courseId: "course-002",
    courseName: "Database Systems Laboratory",
    date: "2023-09-12",
    startTime: "13:00",
    endTime: "15:00",
    location: "Lab Room 102",
    instructor: "Dr. Dewi Anggraini",
    assistants: ["Budi Setiawan", "Rina Fitriani"],
    topic: "Database Design",
    materials: ["ER Diagram tools", "Design documentation"],
    status: "completed",
    attendanceCount: 8,
    totalEnrolled: 8,
  },
  {
    id: "session-008",
    courseId: "course-002",
    courseName: "Database Systems Laboratory",
    date: "2023-09-19",
    startTime: "13:00",
    endTime: "15:00",
    location: "Lab Room 102",
    instructor: "Dr. Dewi Anggraini",
    assistants: ["Budi Setiawan", "Rina Fitriani"],
    topic: "Stored Procedures",
    materials: ["SQL Server", "Procedure templates"],
    status: "completed",
    attendanceCount: 7,
    totalEnrolled: 8,
    notes: "One student had difficulty with parameters",
  },
]

export const mockPracticumSchedules: PracticumSchedule[] = [
  {
    id: "schedule-1",
    title: "Praktikum Basis Data",
    course: "Basis Data",
    day: "Senin",
    startTime: "08:00",
    endTime: "10:00",
    lab: "Lab Database",
    assistants: ["Ahmad Fauzi", "Siti Rahma"],
    status: "active",
  },
  {
    id: "schedule-2",
    title: "Praktikum Algoritma",
    course: "Algoritma dan Pemrograman",
    day: "Senin",
    startTime: "13:00",
    endTime: "15:00",
    lab: "Lab Programming",
    assistants: ["Budi Santoso", "Dewi Anggraini"],
    status: "upcoming",
  },
  {
    id: "schedule-3",
    title: "Praktikum Jaringan Komputer",
    course: "Jaringan Komputer",
    day: "Selasa",
    startTime: "09:00",
    endTime: "11:00",
    lab: "Lab Networking",
    assistants: ["Eko Prasetyo", "Fitri Handayani"],
    status: "upcoming",
  },
  {
    id: "schedule-4",
    title: "Praktikum Pemrograman Web",
    course: "Pemrograman Web",
    day: "Rabu",
    startTime: "10:00",
    endTime: "12:00",
    lab: "Lab Programming",
    assistants: ["Gita Purnama", "Hadi Wijaya"],
    status: "upcoming",
  },
  {
    id: "schedule-5",
    title: "Praktikum Sistem Operasi",
    course: "Sistem Operasi",
    day: "Rabu",
    startTime: "15:00",
    endTime: "17:00",
    lab: "Lab Systems",
    assistants: ["Indra Kusuma", "Joko Santoso"],
    status: "upcoming",
  },
  {
    id: "schedule-6",
    title: "Praktikum Struktur Data",
    course: "Struktur Data",
    day: "Kamis",
    startTime: "08:00",
    endTime: "10:00",
    lab: "Lab Programming",
    assistants: ["Kartika Dewi", "Lina Putri"],
    status: "completed",
  },
  {
    id: "schedule-7",
    title: "Praktikum Keamanan Jaringan",
    course: "Keamanan Jaringan",
    day: "Kamis",
    startTime: "13:00",
    endTime: "15:00",
    lab: "Lab Networking",
    assistants: ["Maman Suryaman", "Nita Anggraini"],
    status: "completed",
  },
  {
    id: "schedule-8",
    title: "Praktikum Pemrograman Mobile",
    course: "Pemrograman Mobile",
    day: "Jumat",
    startTime: "09:00",
    endTime: "11:00",
    lab: "Lab Mobile",
    assistants: ["Oki Prasetyo", "Putri Handayani"],
    status: "cancelled",
  },
  {
    id: "schedule-9",
    title: "Praktikum Kecerdasan Buatan",
    course: "Kecerdasan Buatan",
    day: "Jumat",
    startTime: "13:00",
    endTime: "15:00",
    lab: "Lab AI",
    assistants: ["Qori Maulana", "Rini Susanti"],
    status: "upcoming",
  },
  {
    id: "schedule-10",
    title: "Praktikum Grafika Komputer",
    course: "Grafika Komputer",
    day: "Sabtu",
    startTime: "08:00",
    endTime: "10:00",
    lab: "Lab Multimedia",
    assistants: ["Surya Wijaya", "Tina Agustina"],
    status: "upcoming",
  },
]

