import type { OutstandingStudent } from "@/types/outstanding-student"

export const mockOutstandingStudents: OutstandingStudent[] = [
  {
    id: "os-001",
    name: "Anisa Wijayanti",
    nim: "19201010001",
    department: "Teknik Sipil - Irigasi",
    departmentId: "civil",
    year: 4,
    gpa: 3.92,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Anisa adalah mahasiswa berprestasi yang aktif dalam penelitian infrastruktur berkelanjutan dan telah menerima beberapa penghargaan nasional.",
    achievements: [
      {
        id: "ach-001",
        title: "Juara 1 Lomba Karya Tulis Ilmiah Nasional",
        description:
          "Memenangkan kompetisi karya tulis ilmiah tingkat nasional dengan tema 'Inovasi Infrastruktur Berkelanjutan'.",
        date: "2023-05-15",
        category: "competition",
        level: "national",
      },
      {
        id: "ach-002",
        title: "Publikasi Jurnal Internasional",
        description:
          "Paper berjudul 'Sustainable Irrigation Systems for Urban Areas' diterbitkan di Journal of Civil Engineering.",
        date: "2023-08-20",
        category: "research",
        level: "international",
      },
      {
        id: "ach-003",
        title: "Beasiswa Prestasi Akademik",
        description: "Menerima beasiswa penuh selama 2 tahun berturut-turut berdasarkan prestasi akademik.",
        date: "2022-09-01",
        category: "academic",
        level: "university",
      },
    ],
  },
  {
    id: "os-002",
    name: "Budi Santoso",
    nim: "20201020015",
    department: "Teknik Elektro",
    departmentId: "electrical",
    year: 3,
    gpa: 3.89,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Budi adalah inovator di bidang teknologi energi terbarukan dengan beberapa paten dalam pengembangan.",
    achievements: [
      {
        id: "ach-004",
        title: "Paten Teknologi Energi Terbarukan",
        description:
          "Mendaftarkan paten untuk inovasi 'Smart Solar Energy Converter' yang meningkatkan efisiensi panel surya hingga 25%.",
        date: "2023-03-10",
        category: "research",
        level: "national",
      },
      {
        id: "ach-005",
        title: "Finalis Kompetisi Inovasi Teknologi",
        description: "Menjadi finalis dalam kompetisi inovasi teknologi tingkat Asia Tenggara.",
        date: "2022-11-05",
        category: "competition",
        level: "international",
      },
    ],
  },
  {
    id: "os-003",
    name: "Citra Dewi",
    nim: "21201030022",
    department: "Arsitektur",
    departmentId: "architecture",
    year: 2,
    gpa: 3.95,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Citra adalah mahasiswa arsitektur berbakat yang telah memenangkan beberapa kompetisi desain dan aktif dalam proyek konservasi bangunan bersejarah.",
    achievements: [
      {
        id: "ach-006",
        title: "Juara 1 Kompetisi Desain Arsitektur",
        description: "Memenangkan kompetisi desain arsitektur berkelanjutan tingkat nasional.",
        date: "2023-06-22",
        category: "competition",
        level: "national",
      },
      {
        id: "ach-007",
        title: "Proyek Konservasi Bangunan Bersejarah",
        description: "Memimpin tim mahasiswa dalam proyek konservasi bangunan bersejarah di kota tua.",
        date: "2023-01-15",
        category: "community",
        level: "regional",
      },
    ],
  },
  {
    id: "os-004",
    name: "Dimas Pratama",
    nim: "20201040033",
    department: "Informatika",
    departmentId: "informatics",
    year: 3,
    gpa: 3.91,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Dimas adalah pengembang software berbakat yang telah menciptakan beberapa aplikasi inovatif dan aktif dalam kompetisi pemrograman.",
    achievements: [
      {
        id: "ach-008",
        title: "Juara 2 Hackathon Nasional",
        description:
          "Memenangkan posisi kedua dalam hackathon nasional dengan aplikasi 'EduConnect' untuk pendidikan jarak jauh.",
        date: "2023-07-10",
        category: "competition",
        level: "national",
      },
      {
        id: "ach-009",
        title: "Google Developer Student Club Lead",
        description: "Terpilih sebagai pemimpin Google Developer Student Club untuk universitas.",
        date: "2022-08-15",
        category: "leadership",
        level: "university",
      },
      {
        id: "ach-010",
        title: "Aplikasi dengan 100,000+ Unduhan",
        description: "Mengembangkan aplikasi pembelajaran yang telah diunduh lebih dari 100,000 kali di Play Store.",
        date: "2023-02-28",
        category: "academic",
        level: "national",
      },
    ],
  },
  {
    id: "os-005",
    name: "Eva Maharani",
    nim: "21201050044",
    department: "Perencanaan Wilayah dan Kota",
    departmentId: "urban",
    year: 2,
    gpa: 3.88,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Eva adalah mahasiswa yang fokus pada perencanaan kota berkelanjutan dan telah terlibat dalam beberapa proyek pengembangan masyarakat.",
    achievements: [
      {
        id: "ach-011",
        title: "Proyek Percontohan Kota Hijau",
        description: "Memimpin proyek percontohan 'Kota Hijau' yang diimplementasikan di tiga kelurahan.",
        date: "2023-04-20",
        category: "community",
        level: "regional",
      },
      {
        id: "ach-012",
        title: "Presenter Terbaik di Konferensi Perencanaan Kota",
        description: "Mendapatkan penghargaan presenter terbaik di konferensi perencanaan kota tingkat nasional.",
        date: "2022-12-05",
        category: "academic",
        level: "national",
      },
    ],
  },
  {
    id: "os-006",
    name: "Farhan Akbar",
    nim: "19201010056",
    department: "Teknik Sipil - Irigasi",
    departmentId: "civil",
    year: 4,
    gpa: 3.85,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Farhan adalah peneliti muda di bidang struktur bangunan tahan gempa dan telah berpartisipasi dalam beberapa proyek rekonstruksi pasca bencana.",
    achievements: [
      {
        id: "ach-013",
        title: "Penelitian Struktur Tahan Gempa",
        description:
          "Penelitian tentang struktur bangunan tahan gempa yang mendapatkan hibah penelitian dari kementerian.",
        date: "2023-02-15",
        category: "research",
        level: "national",
      },
      {
        id: "ach-014",
        title: "Relawan Rekonstruksi Pasca Gempa",
        description: "Memimpin tim relawan mahasiswa dalam proyek rekonstruksi pasca gempa di daerah terdampak.",
        date: "2022-10-10",
        category: "community",
        level: "regional",
      },
    ],
  },
  {
    id: "os-007",
    name: "Gita Purnama",
    nim: "20201020067",
    department: "Teknik Elektro",
    departmentId: "electrical",
    year: 3,
    gpa: 3.93,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Gita adalah mahasiswa yang fokus pada pengembangan sistem otomasi industri dan telah memenangkan beberapa kompetisi robotika.",
    achievements: [
      {
        id: "ach-015",
        title: "Juara 1 Kompetisi Robotika Nasional",
        description: "Memenangkan kompetisi robotika nasional dengan robot 'AutoHarvest' untuk otomasi pertanian.",
        date: "2023-08-05",
        category: "competition",
        level: "national",
      },
      {
        id: "ach-016",
        title: "Magang di Perusahaan Otomasi Multinasional",
        description: "Terpilih untuk program magang eksklusif di perusahaan otomasi multinasional selama 6 bulan.",
        date: "2022-07-01",
        category: "academic",
        level: "international",
      },
    ],
  },
  {
    id: "os-008",
    name: "Hadi Wijaya",
    nim: "21201030078",
    department: "Arsitektur",
    departmentId: "architecture",
    year: 2,
    gpa: 3.9,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Hadi adalah mahasiswa arsitektur yang fokus pada desain berkelanjutan dan telah memenangkan beberapa kompetisi desain internasional.",
    achievements: [
      {
        id: "ach-017",
        title: "Finalis Kompetisi Desain Internasional",
        description:
          "Menjadi finalis dalam kompetisi desain arsitektur internasional dengan konsep 'Floating Eco-City'.",
        date: "2023-09-15",
        category: "competition",
        level: "international",
      },
      {
        id: "ach-018",
        title: "Pameran Karya di Galeri Arsitektur",
        description: "Karya desain dipamerkan di galeri arsitektur nasional selama 3 bulan.",
        date: "2023-05-01",
        category: "academic",
        level: "national",
      },
    ],
  },
  {
    id: "os-009",
    name: "Indah Permata",
    nim: "20201040089",
    department: "Informatika",
    departmentId: "informatics",
    year: 3,
    gpa: 3.94,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Indah adalah mahasiswa informatika yang fokus pada kecerdasan buatan dan telah mengembangkan beberapa algoritma inovatif untuk pengenalan pola.",
    achievements: [
      {
        id: "ach-019",
        title: "Paper di Konferensi AI Internasional",
        description: "Paper tentang algoritma pengenalan pola baru diterima di konferensi AI internasional.",
        date: "2023-06-10",
        category: "research",
        level: "international",
      },
      {
        id: "ach-020",
        title: "Beasiswa Penelitian AI",
        description: "Menerima beasiswa penelitian khusus untuk pengembangan aplikasi AI dalam bidang kesehatan.",
        date: "2022-09-20",
        category: "academic",
        level: "national",
      },
      {
        id: "ach-021",
        title: "Juara 1 Kompetisi Data Science",
        description: "Memenangkan kompetisi data science tingkat nasional dengan solusi prediksi penyakit berbasis AI.",
        date: "2023-03-15",
        category: "competition",
        level: "national",
      },
    ],
  },
  {
    id: "os-010",
    name: "Joko Santoso",
    nim: "21201050090",
    department: "Perencanaan Wilayah dan Kota",
    departmentId: "urban",
    year: 2,
    gpa: 3.87,
    photoUrl: "/placeholder.svg?height=150&width=150",
    bio: "Joko adalah mahasiswa yang fokus pada perencanaan transportasi perkotaan dan telah terlibat dalam beberapa proyek pengembangan transportasi publik.",
    achievements: [
      {
        id: "ach-022",
        title: "Proyek Perencanaan Transportasi Publik",
        description: "Mengembangkan rencana transportasi publik terintegrasi yang diadopsi oleh pemerintah kota.",
        date: "2023-07-25",
        category: "community",
        level: "regional",
      },
      {
        id: "ach-023",
        title: "Presenter di Seminar Transportasi Berkelanjutan",
        description: "Menjadi presenter di seminar internasional tentang transportasi berkelanjutan.",
        date: "2023-01-30",
        category: "academic",
        level: "international",
      },
    ],
  },
]

export const getOutstandingStudentsByDepartment = (departmentId: string) => {
  if (departmentId === "all") {
    return mockOutstandingStudents
  }
  return mockOutstandingStudents.filter((student) => student.departmentId === departmentId)
}

export const getOutstandingStudentById = (id: string) => {
  return mockOutstandingStudents.find((student) => student.id === id)
}

