import type { ThesisTitle } from "@/types/thesis"

export const mockArchivedThesisData: ThesisTitle[] = [
  {
    id: "thesis-101",
    title: "Analisis Performa Algoritma Sorting pada Struktur Data yang Berbeda",
    author: {
      id: "std-101",
      name: "Dian Permata",
      nim: "1701234567",
      department: "Teknik Informatika",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    abstract:
      "Penelitian ini menganalisis performa berbagai algoritma sorting seperti Bubble Sort, Quick Sort, dan Merge Sort pada struktur data yang berbeda seperti array, linked list, dan tree. Hasil menunjukkan bahwa Quick Sort memiliki performa terbaik pada array, sementara Merge Sort lebih efisien untuk linked list.",
    keywords: ["algoritma", "sorting", "struktur data", "performa", "kompleksitas"],
    submissionDate: "2018-05-10",
    status: "archived",
    supervisor: {
      id: "sup-101",
      name: "Dr. Hadi Wijaya",
      department: "Teknik Informatika",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    department: "Teknik Informatika",
    year: 2018,
    digitalCopy: true,
    archiveInfo: {
      date: "2018-12-15",
      location: "Perpustakaan Pusat Lt. 3",
      physicalId: "TI-2018-101",
      digitalId: "DIG-2018-101",
      notes: "Kondisi fisik baik, tersedia dalam format digital PDF",
    },
    reviewHistory: [
      {
        id: "rev-101",
        date: "2018-05-10",
        reviewer: "Admin",
        action: "submitted",
      },
      {
        id: "rev-102",
        date: "2018-05-20",
        reviewer: "Dr. Hadi Wijaya",
        action: "approved",
        comments: "Penelitian yang sangat baik dengan metodologi yang kuat.",
      },
      {
        id: "rev-103",
        date: "2018-12-15",
        reviewer: "Admin Perpustakaan",
        action: "archived",
        comments: "Thesis telah selesai dan diarsipkan.",
      },
    ],
  },
  {
    id: "thesis-102",
    title: "Pengembangan Sistem Informasi Akademik Berbasis Web dengan Framework Laravel",
    author: {
      id: "std-102",
      name: "Rudi Hartono",
      nim: "1801234568",
      department: "Sistem Informasi",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    abstract:
      "Penelitian ini mengembangkan sistem informasi akademik berbasis web menggunakan framework Laravel. Sistem ini mencakup fitur manajemen mahasiswa, dosen, mata kuliah, nilai, dan jadwal perkuliahan. Hasil pengujian menunjukkan bahwa sistem ini dapat meningkatkan efisiensi pengelolaan data akademik.",
    keywords: ["sistem informasi", "akademik", "web", "laravel", "database"],
    submissionDate: "2019-06-20",
    status: "archived",
    supervisor: {
      id: "sup-102",
      name: "Dr. Siti Aminah",
      department: "Sistem Informasi",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    department: "Sistem Informasi",
    year: 2019,
    digitalCopy: true,
    archiveInfo: {
      date: "2019-12-10",
      location: "Perpustakaan Pusat Lt. 3",
      physicalId: "SI-2019-102",
      digitalId: "DIG-2019-102",
      notes: "Tersedia dalam format digital PDF dan source code",
    },
    reviewHistory: [
      {
        id: "rev-104",
        date: "2019-06-20",
        reviewer: "Admin",
        action: "submitted",
      },
      {
        id: "rev-105",
        date: "2019-07-05",
        reviewer: "Dr. Siti Aminah",
        action: "approved",
        comments: "Implementasi yang baik dengan dokumentasi yang lengkap.",
      },
      {
        id: "rev-106",
        date: "2019-12-10",
        reviewer: "Admin Perpustakaan",
        action: "archived",
      },
    ],
  },
  {
    id: "thesis-103",
    title: "Analisis Sentimen pada Media Sosial Twitter Menggunakan Metode Naive Bayes",
    author: {
      id: "std-103",
      name: "Maya Putri",
      nim: "1901234569",
      department: "Teknik Informatika",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    abstract:
      "Penelitian ini menganalisis sentimen pengguna Twitter terhadap layanan e-commerce di Indonesia menggunakan metode Naive Bayes. Data diambil dari tweet pengguna selama periode 3 bulan dan diklasifikasikan menjadi sentimen positif, negatif, dan netral. Hasil menunjukkan akurasi klasifikasi sebesar 78%.",
    keywords: ["analisis sentimen", "twitter", "naive bayes", "e-commerce", "klasifikasi"],
    submissionDate: "2020-05-15",
    status: "archived",
    supervisor: {
      id: "sup-103",
      name: "Prof. Bambang Sutejo",
      department: "Teknik Informatika",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    department: "Teknik Informatika",
    year: 2020,
    digitalCopy: true,
    archiveInfo: {
      date: "2020-11-20",
      location: "Perpustakaan Pusat Lt. 3",
      physicalId: "TI-2020-103",
      digitalId: "DIG-2020-103",
      notes: "Tersedia dalam format digital PDF dan dataset",
    },
    reviewHistory: [
      {
        id: "rev-107",
        date: "2020-05-15",
        reviewer: "Admin",
        action: "submitted",
      },
      {
        id: "rev-108",
        date: "2020-05-30",
        reviewer: "Prof. Bambang Sutejo",
        action: "approved",
        comments: "Analisis yang komprehensif dengan metodologi yang baik.",
      },
      {
        id: "rev-109",
        date: "2020-11-20",
        reviewer: "Admin Perpustakaan",
        action: "archived",
      },
    ],
  },
  {
    id: "thesis-104",
    title: "Implementasi Internet of Things untuk Smart Home dengan Raspberry Pi",
    author: {
      id: "std-104",
      name: "Budi Santoso",
      nim: "1701234570",
      department: "Teknik Elektro",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    abstract:
      "Penelitian ini mengimplementasikan konsep Internet of Things (IoT) untuk smart home menggunakan Raspberry Pi sebagai kontroler utama. Sistem ini mencakup kontrol lampu, AC, keamanan, dan monitoring energi yang dapat diakses melalui aplikasi mobile. Hasil pengujian menunjukkan sistem dapat berfungsi dengan baik dan menghemat energi hingga 30%.",
    keywords: ["internet of things", "smart home", "raspberry pi", "automation", "energy saving"],
    submissionDate: "2017-06-10",
    status: "archived",
    supervisor: {
      id: "sup-104",
      name: "Dr. Eko Prasetyo",
      department: "Teknik Elektro",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    department: "Teknik Elektro",
    year: 2017,
    digitalCopy: false,
    archiveInfo: {
      date: "2017-12-05",
      location: "Perpustakaan Pusat Lt. 3",
      physicalId: "TE-2017-104",
      notes: "Hanya tersedia dalam bentuk fisik, belum didigitalisasi",
    },
    reviewHistory: [
      {
        id: "rev-110",
        date: "2017-06-10",
        reviewer: "Admin",
        action: "submitted",
      },
      {
        id: "rev-111",
        date: "2017-06-25",
        reviewer: "Dr. Eko Prasetyo",
        action: "approved",
        comments: "Implementasi yang inovatif dengan aplikasi praktis.",
      },
      {
        id: "rev-112",
        date: "2017-12-05",
        reviewer: "Admin Perpustakaan",
        action: "archived",
      },
    ],
  },
  {
    id: "thesis-105",
    title: "Pengembangan Game Edukasi untuk Pembelajaran Matematika Tingkat Sekolah Dasar",
    author: {
      id: "std-105",
      name: "Dewi Lestari",
      nim: "1801234571",
      department: "Sistem Informasi",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    abstract:
      "Penelitian ini mengembangkan game edukasi untuk pembelajaran matematika tingkat sekolah dasar. Game ini dirancang dengan pendekatan gamifikasi untuk meningkatkan motivasi dan pemahaman siswa terhadap konsep matematika dasar. Hasil uji coba pada 50 siswa menunjukkan peningkatan nilai rata-rata sebesar 25%.",
    keywords: ["game edukasi", "matematika", "gamifikasi", "pembelajaran", "sekolah dasar"],
    submissionDate: "2019-05-20",
    status: "archived",
    supervisor: {
      id: "sup-105",
      name: "Dr. Rina Wijaya",
      department: "Sistem Informasi",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    department: "Sistem Informasi",
    year: 2019,
    digitalCopy: true,
    archiveInfo: {
      date: "2019-11-15",
      location: "Perpustakaan Pusat Lt. 3",
      physicalId: "SI-2019-105",
      digitalId: "DIG-2019-105",
      notes: "Tersedia dalam format digital PDF dan aplikasi game",
    },
    reviewHistory: [
      {
        id: "rev-113",
        date: "2019-05-20",
        reviewer: "Admin",
        action: "submitted",
      },
      {
        id: "rev-114",
        date: "2019-06-05",
        reviewer: "Dr. Rina Wijaya",
        action: "approved",
        comments: "Pendekatan yang kreatif dengan hasil yang terukur.",
      },
      {
        id: "rev-115",
        date: "2019-11-15",
        reviewer: "Admin Perpustakaan",
        action: "archived",
      },
    ],
  },
  {
    id: "thesis-106",
    title: "Analisis dan Perancangan Jaringan Komputer untuk Kampus Universitas XYZ",
    author: {
      id: "std-106",
      name: "Andi Susanto",
      nim: "1701234572",
      department: "Teknik Informatika",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    abstract:
      "Penelitian ini menganalisis dan merancang jaringan komputer untuk kampus Universitas XYZ. Perancangan mencakup topologi jaringan, konfigurasi router dan switch, serta implementasi keamanan jaringan. Hasil implementasi menunjukkan peningkatan kecepatan transfer data dan keamanan jaringan yang lebih baik.",
    keywords: ["jaringan komputer", "topologi", "router", "switch", "keamanan jaringan"],
    submissionDate: "2018-06-15",
    status: "archived",
    supervisor: {
      id: "sup-106",
      name: "Dr. Agus Santoso",
      department: "Teknik Informatika",
      avatarUrl: "/placeholder.svg?height=40&width=40",
    },
    department: "Teknik Informatika",
    year: 2018,
    digitalCopy: false,
    archiveInfo: {
      date: "2018-12-10",
      location: "Perpustakaan Pusat Lt. 3",
      physicalId: "TI-2018-106",
      notes: "Hanya tersedia dalam bentuk fisik, belum didigitalisasi",
    },
    reviewHistory: [
      {
        id: "rev-116",
        date: "2018-06-15",
        reviewer: "Admin",
        action: "submitted",
      },
      {
        id: "rev-117",
        date: "2018-07-01",
        reviewer: "Dr. Agus Santoso",
        action: "approved",
        comments: "Perancangan yang detail dengan implementasi yang baik.",
      },
      {
        id: "rev-118",
        date: "2018-12-10",
        reviewer: "Admin Perpustakaan",
        action: "archived",
      },
    ],
  },
]

