import type { KkpLocation, KkpTeam, StudentKkpRecord } from "./types"

// Mock KKP Locations
export const mockKkpLocations: KkpLocation[] = [
  {
    id: "loc-001",
    name: "PT Teknologi Maju Indonesia",
    type: "company",
    address: "Jl. Sudirman No. 123",
    city: "Jakarta",
    province: "DKI Jakarta",
    postalCode: "12930",
    contactPerson: "Budi Santoso",
    contactPosition: "HR Manager",
    contactEmail: "budi@teknoindo.com",
    contactPhone: "081234567890",
    website: "www.teknoindo.com",
    description: "Perusahaan teknologi yang bergerak di bidang pengembangan software dan konsultasi IT.",
    submittedBy: {
      id: "std-001",
      name: "Ahmad Rizky",
      nim: "1234567890",
      major: "Informatika",
      semester: 6,
      email: "ahmad@university.ac.id",
      phone: "081234567891",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    submissionDate: "2023-09-15T08:30:00Z",
    status: "pending",
    availablePositions: ["Software Developer", "UI/UX Designer", "QA Engineer"],
    requiredSkills: ["Java", "React", "Node.js", "UI/UX Design"],
  },
  {
    id: "loc-002",
    name: "Dinas Komunikasi dan Informatika",
    type: "government",
    address: "Jl. Merdeka No. 45",
    city: "Bandung",
    province: "Jawa Barat",
    postalCode: "40115",
    contactPerson: "Siti Rahayu",
    contactPosition: "Kepala Bidang IT",
    contactEmail: "siti@diskominfo.go.id",
    contactPhone: "081234567892",
    website: "www.diskominfo.go.id",
    description: "Dinas pemerintah yang mengelola teknologi informasi dan komunikasi di tingkat kota.",
    submittedBy: {
      id: "std-002",
      name: "Dewi Anggraini",
      nim: "1234567891",
      major: "Sistem Informasi",
      semester: 6,
      email: "dewi@university.ac.id",
      phone: "081234567893",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    submissionDate: "2023-09-10T10:15:00Z",
    status: "approved",
    reviewedBy: "Dr. Hadi Santoso",
    reviewDate: "2023-09-12T14:30:00Z",
    availablePositions: ["Web Developer", "Network Engineer", "Data Analyst"],
    requiredSkills: ["PHP", "MySQL", "Network Management", "Data Analysis"],
  },
  {
    id: "loc-003",
    name: "Universitas Teknologi Indonesia",
    type: "education",
    address: "Jl. Pendidikan No. 78",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    postalCode: "55281",
    contactPerson: "Dr. Bambang Wijaya",
    contactPosition: "Kepala Laboratorium Komputer",
    contactEmail: "bambang@uti.ac.id",
    contactPhone: "081234567894",
    website: "www.uti.ac.id",
    description: "Universitas yang fokus pada pendidikan teknologi dan penelitian.",
    submittedBy: {
      id: "std-003",
      name: "Rudi Hartono",
      nim: "1234567892",
      major: "Teknik Komputer",
      semester: 6,
      email: "rudi@university.ac.id",
      phone: "081234567895",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    submissionDate: "2023-09-08T09:45:00Z",
    status: "rejected",
    reviewedBy: "Dr. Hadi Santoso",
    reviewDate: "2023-09-11T11:20:00Z",
    feedback:
      "Lokasi tidak sesuai dengan kebutuhan program KKP. Silakan cari lokasi lain yang lebih relevan dengan bidang studi.",
    availablePositions: ["Lab Assistant", "Research Assistant"],
    requiredSkills: ["Hardware Programming", "Embedded Systems", "IoT"],
  },
  {
    id: "loc-004",
    name: "Startup Digital Nusantara",
    type: "company",
    address: "Jl. Gatot Subroto No. 56",
    city: "Surabaya",
    province: "Jawa Timur",
    postalCode: "60271",
    contactPerson: "Andi Pratama",
    contactPosition: "CEO",
    contactEmail: "andi@startupdigital.com",
    contactPhone: "081234567896",
    website: "www.startupdigital.com",
    description: "Startup yang bergerak di bidang fintech dan e-commerce.",
    submittedBy: {
      id: "std-004",
      name: "Nina Sari",
      nim: "1234567893",
      major: "Informatika",
      semester: 6,
      email: "nina@university.ac.id",
      phone: "081234567897",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    submissionDate: "2023-09-05T13:20:00Z",
    status: "approved",
    reviewedBy: "Dr. Hadi Santoso",
    reviewDate: "2023-09-07T15:45:00Z",
    availablePositions: ["Mobile Developer", "Backend Developer", "Frontend Developer"],
    requiredSkills: ["Flutter", "React Native", "Spring Boot", "React"],
  },
  {
    id: "loc-005",
    name: "Yayasan Teknologi untuk Semua",
    type: "non-profit",
    address: "Jl. Cendrawasih No. 34",
    city: "Malang",
    province: "Jawa Timur",
    postalCode: "65145",
    contactPerson: "Maya Indah",
    contactPosition: "Program Manager",
    contactEmail: "maya@techforall.org",
    contactPhone: "081234567898",
    website: "www.techforall.org",
    description: "Yayasan yang fokus pada pendidikan teknologi untuk masyarakat kurang mampu.",
    submittedBy: {
      id: "std-005",
      name: "Bima Sakti",
      nim: "1234567894",
      major: "Sistem Informasi",
      semester: 6,
      email: "bima@university.ac.id",
      phone: "081234567899",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    submissionDate: "2023-09-03T11:10:00Z",
    status: "pending",
    availablePositions: ["IT Trainer", "Web Developer", "Content Creator"],
    requiredSkills: ["Teaching", "Web Development", "Content Creation"],
  },
]

// Mock KKP Teams
export const mockKkpTeams: KkpTeam[] = [
  {
    id: "team-001",
    name: "Tech Innovators",
    location: mockKkpLocations[0],
    members: [
      {
        id: "std-001",
        name: "Ahmad Rizky",
        nim: "1234567890",
        major: "Informatika",
        semester: 6,
        email: "ahmad@university.ac.id",
        phone: "081234567891",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "std-006",
        name: "Dian Permata",
        nim: "1234567895",
        major: "Informatika",
        semester: 6,
        email: "dian@university.ac.id",
        phone: "081234567900",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    leader: {
      id: "std-001",
      name: "Ahmad Rizky",
      nim: "1234567890",
      major: "Informatika",
      semester: 6,
      email: "ahmad@university.ac.id",
      phone: "081234567891",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-10-01T00:00:00Z",
    endDate: "2023-12-31T00:00:00Z",
    submissionDate: "2023-09-20T09:30:00Z",
    status: "pending",
    projectTitle: "Pengembangan Aplikasi Mobile untuk Manajemen Inventaris",
    projectDescription:
      "Mengembangkan aplikasi mobile untuk memudahkan manajemen inventaris perusahaan dengan fitur scanning barcode dan integrasi dengan sistem ERP.",
  },
  {
    id: "team-002",
    name: "Digital Governance",
    location: mockKkpLocations[1],
    members: [
      {
        id: "std-002",
        name: "Dewi Anggraini",
        nim: "1234567891",
        major: "Sistem Informasi",
        semester: 6,
        email: "dewi@university.ac.id",
        phone: "081234567893",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "std-007",
        name: "Fajar Ramadhan",
        nim: "1234567896",
        major: "Sistem Informasi",
        semester: 6,
        email: "fajar@university.ac.id",
        phone: "081234567901",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "std-008",
        name: "Gita Nirmala",
        nim: "1234567897",
        major: "Sistem Informasi",
        semester: 6,
        email: "gita@university.ac.id",
        phone: "081234567902",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    leader: {
      id: "std-002",
      name: "Dewi Anggraini",
      nim: "1234567891",
      major: "Sistem Informasi",
      semester: 6,
      email: "dewi@university.ac.id",
      phone: "081234567893",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    supervisor: {
      id: "sup-001",
      name: "Dr. Eko Prasetyo",
      nip: "198501152010121002",
      department: "Sistem Informasi",
      email: "eko@university.ac.id",
      phone: "081234567903",
      specialization: "E-Government",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    companyMentor: {
      name: "Siti Rahayu",
      position: "Kepala Bidang IT",
      email: "siti@diskominfo.go.id",
      phone: "081234567892",
    },
    startDate: "2023-10-01T00:00:00Z",
    endDate: "2023-12-31T00:00:00Z",
    submissionDate: "2023-09-18T14:45:00Z",
    status: "approved",
    reviewedBy: "Dr. Hadi Santoso",
    reviewDate: "2023-09-19T10:30:00Z",
    projectTitle: "Pengembangan Sistem Informasi Pelayanan Publik",
    projectDescription:
      "Mengembangkan sistem informasi untuk meningkatkan efisiensi pelayanan publik dengan fitur antrian online dan tracking status layanan.",
  },
  {
    id: "team-003",
    name: "Mobile Innovators",
    location: mockKkpLocations[3],
    members: [
      {
        id: "std-004",
        name: "Nina Sari",
        nim: "1234567893",
        major: "Informatika",
        semester: 6,
        email: "nina@university.ac.id",
        phone: "081234567897",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "std-009",
        name: "Hendra Wijaya",
        nim: "1234567898",
        major: "Informatika",
        semester: 6,
        email: "hendra@university.ac.id",
        phone: "081234567904",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    leader: {
      id: "std-004",
      name: "Nina Sari",
      nim: "1234567893",
      major: "Informatika",
      semester: 6,
      email: "nina@university.ac.id",
      phone: "081234567897",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-10-01T00:00:00Z",
    endDate: "2023-12-31T00:00:00Z",
    submissionDate: "2023-09-15T11:20:00Z",
    status: "rejected",
    reviewedBy: "Dr. Hadi Santoso",
    reviewDate: "2023-09-17T13:15:00Z",
    feedback:
      "Proposal proyek tidak cukup detail dan tidak sesuai dengan kebutuhan perusahaan. Silakan revisi proposal dengan lebih spesifik tentang tujuan dan hasil yang diharapkan.",
    projectTitle: "Pengembangan Aplikasi Mobile E-Commerce",
    projectDescription:
      "Mengembangkan aplikasi mobile e-commerce dengan fitur pembayaran digital dan integrasi dengan marketplace.",
  },
  {
    id: "team-004",
    name: "Tech for All",
    location: mockKkpLocations[4],
    members: [
      {
        id: "std-005",
        name: "Bima Sakti",
        nim: "1234567894",
        major: "Sistem Informasi",
        semester: 6,
        email: "bima@university.ac.id",
        phone: "081234567899",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
    leader: {
      id: "std-005",
      name: "Bima Sakti",
      nim: "1234567894",
      major: "Sistem Informasi",
      semester: 6,
      email: "bima@university.ac.id",
      phone: "081234567899",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    startDate: "2023-10-01T00:00:00Z",
    endDate: "2023-12-31T00:00:00Z",
    submissionDate: "2023-09-12T10:05:00Z",
    status: "revision-needed",
    reviewedBy: "Dr. Hadi Santoso",
    reviewDate: "2023-09-14T09:45:00Z",
    feedback:
      "Jumlah anggota tim terlalu sedikit untuk proyek yang diusulkan. Silakan tambahkan anggota tim atau sesuaikan skala proyek.",
    projectTitle: "Pelatihan Dasar Pemrograman untuk Masyarakat",
    projectDescription:
      "Mengembangkan modul pelatihan dan melaksanakan pelatihan dasar pemrograman untuk masyarakat kurang mampu.",
  },
]

// Mock Student KKP Records
export const mockStudentKkpRecords: StudentKkpRecord[] = [
  {
    id: "record-001",
    student: mockKkpTeams[1].members[0],
    location: mockKkpLocations[1],
    team: mockKkpTeams[1],
    supervisor: mockKkpTeams[1].supervisor,
    companyMentor: mockKkpTeams[1].companyMentor,
    startDate: "2023-10-01T00:00:00Z",
    endDate: "2023-12-31T00:00:00Z",
    status: "in-progress",
    projectTitle: "Pengembangan Sistem Informasi Pelayanan Publik",
    projectDescription:
      "Mengembangkan sistem informasi untuk meningkatkan efisiensi pelayanan publik dengan fitur antrian online dan tracking status layanan.",
    documents: [
      {
        id: "doc-001",
        name: "Proposal KKP",
        type: "proposal",
        url: "#",
        uploadDate: "2023-09-25T10:30:00Z",
        status: "verified",
      },
      {
        id: "doc-002",
        name: "Surat Penerimaan",
        type: "acceptance-letter",
        url: "#",
        uploadDate: "2023-09-28T14:15:00Z",
        status: "verified",
      },
    ],
  },
  {
    id: "record-002",
    student: mockKkpTeams[1].members[1],
    location: mockKkpLocations[1],
    team: mockKkpTeams[1],
    supervisor: mockKkpTeams[1].supervisor,
    companyMentor: mockKkpTeams[1].companyMentor,
    startDate: "2023-10-01T00:00:00Z",
    endDate: "2023-12-31T00:00:00Z",
    status: "in-progress",
    projectTitle: "Pengembangan Sistem Informasi Pelayanan Publik",
    projectDescription:
      "Mengembangkan sistem informasi untuk meningkatkan efisiensi pelayanan publik dengan fitur antrian online dan tracking status layanan.",
    documents: [
      {
        id: "doc-003",
        name: "Proposal KKP",
        type: "proposal",
        url: "#",
        uploadDate: "2023-09-25T10:30:00Z",
        status: "verified",
      },
      {
        id: "doc-004",
        name: "Surat Penerimaan",
        type: "acceptance-letter",
        url: "#",
        uploadDate: "2023-09-28T14:15:00Z",
        status: "verified",
      },
    ],
  },
  {
    id: "record-003",
    student: mockKkpTeams[1].members[2],
    location: mockKkpLocations[1],
    team: mockKkpTeams[1],
    supervisor: mockKkpTeams[1].supervisor,
    companyMentor: mockKkpTeams[1].companyMentor,
    startDate: "2023-10-01T00:00:00Z",
    endDate: "2023-12-31T00:00:00Z",
    status: "in-progress",
    projectTitle: "Pengembangan Sistem Informasi Pelayanan Publik",
    projectDescription:
      "Mengembangkan sistem informasi untuk meningkatkan efisiensi pelayanan publik dengan fitur antrian online dan tracking status layanan.",
    documents: [
      {
        id: "doc-005",
        name: "Proposal KKP",
        type: "proposal",
        url: "#",
        uploadDate: "2023-09-25T10:30:00Z",
        status: "verified",
      },
      {
        id: "doc-006",
        name: "Surat Penerimaan",
        type: "acceptance-letter",
        url: "#",
        uploadDate: "2023-09-28T14:15:00Z",
        status: "verified",
      },
    ],
  },
  {
    id: "record-004",
    student: {
      id: "std-010",
      name: "Indra Kusuma",
      nim: "1234567899",
      major: "Informatika",
      semester: 8,
      email: "indra@university.ac.id",
      phone: "081234567905",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    location: {
      id: "loc-006",
      name: "PT Global Tech Solutions",
      type: "company",
      address: "Jl. Thamrin No. 56",
      city: "Jakarta",
      province: "DKI Jakarta",
      postalCode: "10350",
      contactPerson: "Joko Widodo",
      contactPosition: "CTO",
      contactEmail: "joko@globaltech.com",
      contactPhone: "081234567906",
      website: "www.globaltech.com",
      description: "Perusahaan konsultan IT yang menyediakan solusi teknologi untuk berbagai industri.",
      submittedBy: {
        id: "std-010",
        name: "Indra Kusuma",
        nim: "1234567899",
        major: "Informatika",
        semester: 8,
        email: "indra@university.ac.id",
        phone: "081234567905",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      submissionDate: "2023-06-10T09:15:00Z",
      status: "approved",
      reviewedBy: "Dr. Hadi Santoso",
      reviewDate: "2023-06-12T11:30:00Z",
      availablePositions: ["Software Engineer", "System Analyst", "Project Manager"],
      requiredSkills: ["Java", "Spring Boot", "React", "Project Management"],
    },
    supervisor: {
      id: "sup-002",
      name: "Dr. Siti Aminah",
      nip: "197605202005012001",
      department: "Informatika",
      email: "siti@university.ac.id",
      phone: "081234567907",
      specialization: "Software Engineering",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    companyMentor: {
      name: "Joko Widodo",
      position: "CTO",
      email: "joko@globaltech.com",
      phone: "081234567906",
    },
    startDate: "2023-07-01T00:00:00Z",
    endDate: "2023-09-30T00:00:00Z",
    status: "completed",
    projectTitle: "Pengembangan Sistem Manajemen Proyek Berbasis Cloud",
    projectDescription:
      "Mengembangkan sistem manajemen proyek berbasis cloud dengan fitur kolaborasi tim dan integrasi dengan berbagai tools development.",
    grade: "A",
    reportSubmissionDate: "2023-09-25T14:30:00Z",
    presentationDate: "2023-09-28T10:00:00Z",
    completionDate: "2023-09-30T00:00:00Z",
    feedback:
      "Mahasiswa menunjukkan kinerja yang sangat baik selama KKP. Proyek yang dikembangkan telah diimplementasikan dan digunakan oleh perusahaan.",
    documents: [
      {
        id: "doc-007",
        name: "Proposal KKP",
        type: "proposal",
        url: "#",
        uploadDate: "2023-06-20T11:45:00Z",
        status: "verified",
      },
      {
        id: "doc-008",
        name: "Surat Penerimaan",
        type: "acceptance-letter",
        url: "#",
        uploadDate: "2023-06-25T09:30:00Z",
        status: "verified",
      },
      {
        id: "doc-009",
        name: "Laporan KKP",
        type: "report",
        url: "#",
        uploadDate: "2023-09-25T14:30:00Z",
        status: "verified",
      },
      {
        id: "doc-010",
        name: "Sertifikat KKP",
        type: "certificate",
        url: "#",
        uploadDate: "2023-09-30T15:20:00Z",
        status: "verified",
      },
    ],
  },
  {
    id: "record-005",
    student: {
      id: "std-011",
      name: "Laras Wulandari",
      nim: "1234567900",
      major: "Sistem Informasi",
      semester: 8,
      email: "laras@university.ac.id",
      phone: "081234567908",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    location: {
      id: "loc-007",
      name: "Bank Digital Indonesia",
      type: "company",
      address: "Jl. Kuningan No. 78",
      city: "Jakarta",
      province: "DKI Jakarta",
      postalCode: "12940",
      contactPerson: "Diana Putri",
      contactPosition: "Head of IT",
      contactEmail: "diana@bdi.co.id",
      contactPhone: "081234567909",
      website: "www.bdi.co.id",
      description: "Bank digital yang menyediakan layanan perbankan modern berbasis teknologi.",
      submittedBy: {
        id: "std-011",
        name: "Laras Wulandari",
        nim: "1234567900",
        major: "Sistem Informasi",
        semester: 8,
        email: "laras@university.ac.id",
        phone: "081234567908",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      submissionDate: "2023-06-05T13:45:00Z",
      status: "approved",
      reviewedBy: "Dr. Hadi Santoso",
      reviewDate: "2023-06-07T10:15:00Z",
      availablePositions: ["Business Analyst", "System Analyst", "UI/UX Designer"],
      requiredSkills: ["Business Analysis", "System Design", "UI/UX Design", "Banking Knowledge"],
    },
    supervisor: {
      id: "sup-003",
      name: "Dr. Budi Santoso",
      nip: "198103152008011003",
      department: "Sistem Informasi",
      email: "budi@university.ac.id",
      phone: "081234567910",
      specialization: "Business Information Systems",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    companyMentor: {
      name: "Diana Putri",
      position: "Head of IT",
      email: "diana@bdi.co.id",
      phone: "081234567909",
    },
    startDate: "2023-07-01T00:00:00Z",
    endDate: "2023-09-30T00:00:00Z",
    status: "completed",
    projectTitle: "Analisis dan Desain Sistem Mobile Banking",
    projectDescription:
      "Melakukan analisis kebutuhan dan desain sistem mobile banking dengan fokus pada user experience dan keamanan transaksi.",
    grade: "A-",
    reportSubmissionDate: "2023-09-27T16:45:00Z",
    presentationDate: "2023-09-29T13:30:00Z",
    completionDate: "2023-09-30T00:00:00Z",
    feedback:
      "Mahasiswa menunjukkan kemampuan analisis yang baik dan menghasilkan desain sistem yang inovatif. Beberapa rekomendasi telah diimplementasikan oleh perusahaan.",
    documents: [
      {
        id: "doc-011",
        name: "Proposal KKP",
        type: "proposal",
        url: "#",
        uploadDate: "2023-06-15T10:30:00Z",
        status: "verified",
      },
      {
        id: "doc-012",
        name: "Surat Penerimaan",
        type: "acceptance-letter",
        url: "#",
        uploadDate: "2023-06-20T14:15:00Z",
        status: "verified",
      },
      {
        id: "doc-013",
        name: "Laporan KKP",
        type: "report",
        url: "#",
        uploadDate: "2023-09-27T16:45:00Z",
        status: "verified",
      },
      {
        id: "doc-014",
        name: "Sertifikat KKP",
        type: "certificate",
        url: "#",
        uploadDate: "2023-09-30T16:10:00Z",
        status: "verified",
      },
    ],
  },
]

