import type { ExamSchedule } from "./types"

export const mockExamSchedules: ExamSchedule[] = [
  {
    id: "es-001",
    title: "Implementasi Deep Learning untuk Deteksi Penyakit pada Tanaman Padi",
    studentName: "Ahmad Fauzi",
    studentId: "1901234567",
    program: "Informatika",
    examType: "proposal",
    scheduledDate: "2023-11-15T09:00:00Z",
    duration: 120,
    location: "Ruang Seminar A1.2",
    verificationStatus: "pending",
    committee: [
      {
        id: "lec-101",
        name: "Dr. Ahmad Dahlan",
        role: "Ketua Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-102",
        name: "Dr. Kartini Wijaya",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-103",
        name: "Dr. Hatta Rajasa",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
    ],
  },
  {
    id: "es-002",
    title: "Analisis Sentimen pada Media Sosial Twitter Terhadap Kebijakan Pendidikan di Indonesia",
    studentName: "Siti Nurhaliza",
    studentId: "1901234568",
    program: "Informatika",
    examType: "proposal",
    scheduledDate: "2023-11-16T13:00:00Z",
    duration: 120,
    location: "Ruang Seminar B2.3",
    verificationStatus: "verified",
    committee: [
      {
        id: "lec-104",
        name: "Dr. Fatmawati Soekarno",
        role: "Ketua Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-105",
        name: "Dr. Soedirman Prawiro",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-106",
        name: "Dr. Megawati Thamrin",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
    ],
  },
  {
    id: "es-003",
    title: "Pengembangan Sistem Rekomendasi Buku Berbasis Collaborative Filtering",
    studentName: "Muhammad Rizki",
    studentId: "1901234569",
    program: "Informatika",
    examType: "result",
    scheduledDate: "2023-11-20T10:00:00Z",
    duration: 150,
    location: "Ruang Seminar A1.3",
    verificationStatus: "pending",
    committee: [
      {
        id: "lec-107",
        name: "Dr. Soekarno Hatta",
        role: "Ketua Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-108",
        name: "Dr. Cut Nyak Dien",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-101",
        name: "Dr. Ahmad Dahlan",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
    ],
  },
  {
    id: "es-004",
    title: "Implementasi Blockchain untuk Sistem Manajemen Rantai Pasok Produk Pertanian",
    studentName: "Dian Permata",
    studentId: "1901234570",
    program: "Informatika",
    examType: "proposal",
    scheduledDate: "2023-11-22T14:00:00Z",
    duration: 120,
    location: "Ruang Seminar C3.1",
    verificationStatus: "rescheduled",
    notes: "Jadwal diubah dari tanggal 20 November karena ketidaktersediaan ruangan.",
    committee: [
      {
        id: "lec-102",
        name: "Dr. Kartini Wijaya",
        role: "Ketua Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-103",
        name: "Dr. Hatta Rajasa",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-104",
        name: "Dr. Fatmawati Soekarno",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
    ],
  },
  {
    id: "es-005",
    title: "Optimasi Rute Pengiriman Barang Menggunakan Algoritma Genetika",
    studentName: "Budi Santoso",
    studentId: "1901234572",
    program: "Informatika",
    examType: "final",
    scheduledDate: "2023-11-28T10:00:00Z",
    duration: 180,
    location: "Ruang Sidang Utama",
    verificationStatus: "pending",
    committee: [
      {
        id: "lec-105",
        name: "Dr. Soedirman Prawiro",
        role: "Ketua Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-106",
        name: "Dr. Megawati Thamrin",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-107",
        name: "Dr. Soekarno Hatta",
        role: "Penguji",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
      {
        id: "lec-108",
        name: "Dr. Cut Nyak Dien",
        role: "Sekretaris",
        avatarUrl: "/placeholder.svg?height=40&width=40",
      },
    ],
  },
]

