import type { SupervisorExaminerData } from "./types"

export const mockSupervisorExaminerData: SupervisorExaminerData[] = [
  {
    id: "se-001",
    title: "Implementasi Deep Learning untuk Deteksi Penyakit pada Tanaman Padi",
    studentName: "Ahmad Fauzi",
    student_id: "1901234567",
    program: "Informatika",
    exam_type: "proposal",
    status: "complete",
    supervisors: [
      {
        id: "lec-101",
        name: "Dr. Ahmad Dahlan",
        department: "Computer Science",
        expertise: "Artificial Intelligence",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Pembimbing Utama",
      },
      {
        id: "lec-102",
        name: "Dr. Kartini Wijaya",
        department: "Information Systems",
        expertise: "Database Systems",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Pembimbing Pendamping",
      },
    ],
    examiners: [
      {
        id: "lec-103",
        name: "Dr. Hatta Rajasa",
        department: "Computer Science",
        expertise: "Computer Networks",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Ketua Penguji",
      },
      {
        id: "lec-104",
        name: "Dr. Fatmawati Soekarno",
        department: "Information Systems",
        expertise: "Human-Computer Interaction",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Penguji",
      },
      {
        id: "lec-105",
        name: "Dr. Soedirman Prawiro",
        department: "Computer Science",
        expertise: "Machine Learning",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Penguji",
      },
    ],
  },
  {
    id: "se-002",
    title: "Analisis Sentimen pada Media Sosial Twitter Terhadap Kebijakan Pendidikan di Indonesia",
    studentName: "Siti Nurhaliza",
    student_id: "1901234568",
    program: "Informatika",
    exam_type: "proposal",
    status: "partial",
    supervisors: [
      {
        id: "lec-106",
        name: "Dr. Megawati Thamrin",
        department: "Information Systems",
        expertise: "Information Security",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Pembimbing Utama",
      },
    ],
    examiners: [],
  },
  {
    id: "se-003",
    title: "Pengembangan Sistem Rekomendasi Buku Berbasis Collaborative Filtering",
    studentName: "Muhammad Rizki",
    student_id: "1901234569",
    program: "Informatika",
    exam_type: "result",
    status: "pending",
    supervisors: [],
    examiners: [],
  },
  {
    id: "se-004",
    title: "Implementasi Blockchain untuk Sistem Manajemen Rantai Pasok Produk Pertanian",
    studentName: "Dian Permata",
    student_id: "1901234570",
    program: "Informatika",
    exam_type: "proposal",
    status: "partial",
    supervisors: [
      {
        id: "lec-107",
        name: "Dr. Soekarno Hatta",
        department: "Computer Science",
        expertise: "Software Engineering",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Pembimbing Utama",
      },
    ],
    examiners: [
      {
        id: "lec-108",
        name: "Dr. Cut Nyak Dien",
        department: "Information Systems",
        expertise: "Data Mining",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Ketua Penguji",
      },
    ],
  },
  {
    id: "se-005",
    title: "Pengembangan Aplikasi Mobile untuk Monitoring Kesehatan Mental Mahasiswa",
    studentName: "Rina Fitriani",
    student_id: "1901234571",
    program: "Informatika",
    exam_type: "proposal",
    status: "complete",
    supervisors: [
      {
        id: "lec-101",
        name: "Dr. Ahmad Dahlan",
        department: "Computer Science",
        expertise: "Artificial Intelligence",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Pembimbing Utama",
      },
    ],
    examiners: [
      {
        id: "lec-102",
        name: "Dr. Kartini Wijaya",
        department: "Information Systems",
        expertise: "Database Systems",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Ketua Penguji",
      },
      {
        id: "lec-103",
        name: "Dr. Hatta Rajasa",
        department: "Computer Science",
        expertise: "Computer Networks",
        avatarUrl: "/placeholder.svg?height=40&width=40",
        role: "Penguji",
      },
    ],
  },
  {
    id: "se-006",
    title: "Optimasi Rute Pengiriman Barang Menggunakan Algoritma Genetika",
    studentName: "Budi Santoso",
    student_id: "1901234572",
    program: "Informatika",
    exam_type: "final",
    status: "pending",
    supervisors: [],
    examiners: [],
  },
]

