import type { Lecturer } from "./types"

export const mockLecturers: Lecturer[] = [
  {
    id: "lec-101",
    name: "Dr. Ahmad Dahlan",
    department: "Computer Science",
    expertise: "Artificial Intelligence",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-102",
    name: "Dr. Kartini Wijaya",
    department: "Information Systems",
    expertise: "Database Systems",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-103",
    name: "Dr. Hatta Rajasa",
    department: "Computer Science",
    expertise: "Computer Networks",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-104",
    name: "Dr. Fatmawati Soekarno",
    department: "Information Systems",
    expertise: "Human-Computer Interaction",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-105",
    name: "Dr. Soedirman Prawiro",
    department: "Computer Science",
    expertise: "Machine Learning",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-106",
    name: "Dr. Megawati Thamrin",
    department: "Information Systems",
    expertise: "Information Security",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-107",
    name: "Dr. Soekarno Hatta",
    department: "Computer Science",
    expertise: "Software Engineering",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-108",
    name: "Dr. Cut Nyak Dien",
    department: "Information Systems",
    expertise: "Data Mining",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-109",
    name: "Dr. Bung Tomo",
    department: "Computer Science",
    expertise: "Cybersecurity",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-110",
    name: "Dr. Dewi Sartika",
    department: "Information Systems",
    expertise: "Business Intelligence",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-111",
    name: "Dr. Pattimura Matulessy",
    department: "Computer Science",
    expertise: "Computer Graphics",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-112",
    name: "Dr. Raden Ajeng Kartini",
    department: "Information Systems",
    expertise: "Knowledge Management",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-113",
    name: "Dr. Sultan Hasanuddin",
    department: "Computer Science",
    expertise: "Distributed Systems",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-114",
    name: "Dr. Martha Christina Tiahahu",
    department: "Information Systems",
    expertise: "Enterprise Architecture",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "lec-115",
    name: "Dr. Teuku Umar",
    department: "Computer Science",
    expertise: "Mobile Computing",
    avatarUrl: "/placeholder.svg?height=40&width=40",
  },
]

