import type { Exam } from "@/types/exam"

export const mockExams: Exam[] = [
  {
    id: "exam-1",
    studentName: "Ahmad Fauzi",
    studentNIM: "1234567890",
    program: "Computer Science",
    title: "Implementation of Machine Learning for Predicting Student Performance",
    abstract:
      "This research focuses on implementing machine learning algorithms to predict student academic performance based on various factors such as attendance, participation, and previous grades.",
    submissionDate: "2025-03-01T00:00:00.000Z",
    scheduledDate: "2025-03-15T09:00:00.000Z",
    type: "proposal",
    status: "scheduled",
    committee: [
      { id: "lec-001", name: "Dr. Budi Santoso", role: "Chair", avatar: "/placeholder.svg?height=40&width=40" },
      { id: "lec-002", name: "Dr. Siti Rahayu", role: "Member", avatar: "/placeholder.svg?height=40&width=40" },
      { id: "lec-003", name: "Dr. Joko Widodo", role: "Member", avatar: "/placeholder.svg?height=40&width=40" },
    ],
  },
  {
    id: "exam-2",
    studentName: "Siti Nurhaliza",
    studentNIM: "2345678901",
    program: "Information Systems",
    title: "Analysis of E-Commerce User Experience in Indonesia",
    abstract:
      "This study analyzes the user experience of e-commerce platforms in Indonesia, focusing on usability, accessibility, and customer satisfaction.",
    submissionDate: "2025-03-02T00:00:00.000Z",
    type: "proposal",
    status: "pending",
    documents: [
      {
        id: "doc-1",
        name: "Payment Receipt - Ujian Proposal",
        type: "payment_proof",
        status: "verified",
        uploadDate: "2025-03-01T10:30:00.000Z",
        verificationDate: "2025-03-01T14:45:00.000Z",
        fileUrl: "/placeholder.svg?height=200&width=150",
        fileSize: 245000,
        isSystemGenerated: true,
        notes: "Payment verified by finance department",
      },
      {
        id: "doc-2",
        name: "Academic Transcript",
        type: "transcript",
        status: "verified",
        uploadDate: "2025-03-01T11:15:00.000Z",
        verificationDate: "2025-03-01T15:20:00.000Z",
        fileUrl: "/placeholder.svg?height=200&width=150",
        fileSize: 1250000,
        notes: "Student has completed all required courses",
      },
      {
        id: "doc-3",
        name: "Research Proposal Draft",
        type: "proposal",
        status: "unverified",
        uploadDate: "2025-03-01T12:45:00.000Z",
        fileUrl: "/placeholder.svg?height=200&width=150",
        fileSize: 3450000,
      },
      {
        id: "doc-4",
        name: "Supervisor Approval Letter",
        type: "supervisor_approval",
        status: "unverified",
        uploadDate: "2025-03-01T13:30:00.000Z",
        fileUrl: "/placeholder.svg?height=200&width=150",
        fileSize: 180000,
      },
    ],
  },
  {
    id: "exam-3",
    studentName: "Budi Doremi",
    studentNIM: "3456789012",
    program: "Computer Science",
    title: "Blockchain Implementation for Academic Record Verification",
    abstract:
      "This research proposes a blockchain-based system for verifying academic records, ensuring their authenticity and preventing fraud.",
    submissionDate: "2025-03-03T00:00:00.000Z",
    scheduledDate: "2025-03-20T13:00:00.000Z",
    type: "proposal",
    status: "scheduled",
    committee: [
      { id: "lec-004", name: "Dr. Andi Wijaya", role: "Chair", avatar: "/placeholder.svg?height=40&width=40" },
      { id: "lec-005", name: "Dr. Dewi Sartika", role: "Member", avatar: "/placeholder.svg?height=40&width=40" },
      { id: "lec-006", name: "Dr. Rudi Hartono", role: "Member", avatar: "/placeholder.svg?height=40&width=40" },
    ],
  },
  {
    id: "exam-4",
    studentName: "Dewi Kartika",
    studentNIM: "4567890123",
    program: "Information Systems",
    title: "Impact of Social Media on Student Academic Performance",
    abstract:
      "This study examines the impact of social media usage on the academic performance of university students, considering factors such as time spent, platform used, and purpose of use.",
    submissionDate: "2025-02-15T00:00:00.000Z",
    completionDate: "2025-03-01T00:00:00.000Z",
    type: "proposal",
    status: "passed",
  },
  {
    id: "exam-5",
    studentName: "Rudi Salim",
    studentNIM: "5678901234",
    program: "Computer Science",
    title: "Development of Mobile Application for Campus Navigation",
    abstract:
      "This project involves the development of a mobile application that helps students navigate the university campus, locate classrooms, offices, and facilities.",
    submissionDate: "2025-02-20T00:00:00.000Z",
    completionDate: "2025-03-05T00:00:00.000Z",
    type: "proposal",
    status: "failed",
  },
  {
    id: "exam-6",
    studentName: "Nina Zatulini",
    studentNIM: "6789012345",
    program: "Information Systems",
    title: "Implementation of IoT for Smart Classroom",
    abstract:
      "This research focuses on implementing Internet of Things (IoT) technology to create smart classrooms that enhance the learning experience through automation and data collection.",
    submissionDate: "2025-03-05T00:00:00.000Z",
    type: "result",
    status: "pending",
    documents: [
      {
        id: "doc-5",
        name: "Payment Receipt - Final Exam",
        type: "payment_proof",
        status: "verified",
        uploadDate: "2025-03-04T09:15:00.000Z",
        verificationDate: "2025-03-04T11:30:00.000Z",
        fileUrl: "/placeholder.svg?height=200&width=150",
        fileSize: 230000,
        isSystemGenerated: true,
        notes: "Payment verified by finance department",
      },
      {
        id: "doc-6",
        name: "Final Thesis Draft",
        type: "proposal",
        status: "unverified",
        uploadDate: "2025-03-04T10:20:00.000Z",
        fileUrl: "/placeholder.svg?height=200&width=150",
        fileSize: 5670000,
      },
      {
        id: "doc-7",
        name: "Supervisor Final Approval",
        type: "supervisor_approval",
        status: "rejected",
        uploadDate: "2025-03-04T14:45:00.000Z",
        fileUrl: "/placeholder.svg?height=200&width=150",
        fileSize: 190000,
        notes: "Signature missing, please resubmit with proper signature",
      },
      {
        id: "doc-8",
        name: "Plagiarism Check Report",
        type: "other",
        status: "verified",
        uploadDate: "2025-03-04T16:30:00.000Z",
        verificationDate: "2025-03-04T17:45:00.000Z",
        fileUrl: "/placeholder.svg?height=200&width=150",
        fileSize: 420000,
        notes: "Similarity index: 12% - Acceptable",
      },
    ],
  },
  {
    id: "exam-7",
    studentName: "Andi Maulana",
    studentNIM: "7890123456",
    program: "Computer Science",
    title: "Cybersecurity Awareness Among University Students",
    abstract:
      "This study assesses the level of cybersecurity awareness among university students and proposes strategies to improve their knowledge and practices.",
    submissionDate: "2025-03-06T00:00:00.000Z",
    scheduledDate: "2025-03-25T10:00:00.000Z",
    type: "result",
    status: "scheduled",
    committee: [
      { id: "lec-007", name: "Dr. Hadi Santoso", role: "Chair", avatar: "/placeholder.svg?height=40&width=40" },
      { id: "lec-008", name: "Dr. Maya Angelina", role: "Member", avatar: "/placeholder.svg?height=40&width=40" },
      { id: "lec-009", name: "Dr. Tono Sucipto", role: "Member", avatar: "/placeholder.svg?height=40&width=40" },
    ],
  },
  {
    id: "exam-8",
    studentName: "Maya Sari",
    studentNIM: "8901234567",
    program: "Information Systems",
    title: "Digital Transformation in Higher Education",
    abstract:
      "This research examines the process of digital transformation in higher education institutions, focusing on challenges, opportunities, and best practices.",
    submissionDate: "2025-02-25T00:00:00.000Z",
    completionDate: "2025-03-10T00:00:00.000Z",
    type: "result",
    status: "passed",
  },
  {
    id: "exam-9",
    studentName: "Joko Susilo",
    studentNIM: "9012345678",
    program: "Computer Science",
    title: "Artificial Intelligence for Automated Essay Grading",
    abstract:
      "This study develops and evaluates an artificial intelligence system for automatically grading student essays, considering factors such as content, structure, and grammar.",
    submissionDate: "2025-02-28T00:00:00.000Z",
    completionDate: "2025-03-12T00:00:00.000Z",
    type: "result",
    status: "failed",
  },
  {
    id: "exam-10",
    studentName: "Lina Marlina",
    studentNIM: "0123456789",
    program: "Information Systems",
    title: "Cloud Computing Adoption in Indonesian Universities",
    abstract:
      "This research investigates the adoption of cloud computing in Indonesian universities, examining factors that influence adoption decisions and implementation strategies.",
    submissionDate: "2025-03-07T00:00:00.000Z",
    scheduledDate: "2025-03-30T14:00:00.000Z",
    type: "result",
    status: "scheduled",
    committee: [
      { id: "lec-010", name: "Dr. Bambang Supomo", role: "Chair", avatar: "/placeholder.svg?height=40&width=40" },
      { id: "lec-011", name: "Dr. Ratna Sari", role: "Member", avatar: "/placeholder.svg?height=40&width=40" },
      { id: "lec-012", name: "Dr. Dedi Kurniawan", role: "Member", avatar: "/placeholder.svg?height=40&width=40" },
    ],
  },
]

