import type { BookCategory } from "@/types/book"

export const mockCategories: BookCategory[] = [
  {
    id: "1",
    code: "FIK",
    name: "Fiksi",
    description: "Buku-buku fiksi termasuk novel, cerpen, dan karya sastra lainnya",
    bookCount: 156,
    isActive: true,
  },
  {
    id: "2",
    code: "KOMP",
    name: "Ilmu Komputer",
    description: "Buku-buku tentang pemrograman, jaringan, dan teknologi informasi",
    bookCount: 89,
    isActive: true,
  },
  {
    id: "3",
    code: "HKM",
    name: "Hukum",
    description: "Buku-buku tentang hukum dan perundang-undangan",
    bookCount: 67,
    isActive: true,
  },
  {
    id: "4",
    code: "EKO",
    name: "Ekonomi",
    description: "Buku-buku tentang ekonomi, bisnis, dan manajemen",
    bookCount: 78,
    isActive: true,
  },
  {
    id: "5",
    code: "PSI",
    name: "Psikologi",
    description: "Buku-buku tentang psikologi dan kesehatan mental",
    bookCount: 45,
    isActive: true,
  },
  {
    id: "6",
    code: "SAINS",
    name: "Sains",
    description: "Buku-buku tentang fisika, kimia, biologi, dan ilmu pengetahuan alam lainnya",
    bookCount: 92,
    isActive: true,
  },
  {
    id: "7",
    code: "AGAMA",
    name: "Agama",
    description: "Buku-buku tentang agama dan spiritualitas",
    bookCount: 53,
    isActive: true,
  },
  {
    id: "8",
    code: "SENI",
    name: "Seni dan Budaya",
    description: "Buku-buku tentang seni, musik, film, dan budaya",
    bookCount: 34,
    isActive: true,
  },
  {
    id: "9",
    code: "SEJARAH",
    name: "Sejarah",
    description: "Buku-buku tentang sejarah dunia dan Indonesia",
    bookCount: 61,
    isActive: true,
  },
  {
    id: "10",
    code: "FILSAFAT",
    name: "Filsafat",
    description: "Buku-buku tentang filsafat dan pemikiran",
    bookCount: 28,
    isActive: true,
  },
  {
    id: "11",
    code: "KOMIK",
    name: "Komik dan Manga",
    description: "Koleksi komik dan manga",
    bookCount: 112,
    isActive: true,
  },
  {
    id: "12",
    code: "ARSIP",
    name: "Arsip Lama",
    description: "Buku-buku arsip yang jarang diakses",
    bookCount: 17,
    isActive: false,
  },
]

