import type { LabAssistant } from "./types"

export const mockLabAssistants: LabAssistant[] = [
  {
    id: "1",
    name: "Ahmad Fauzi",
    studentId: "2020573010",
    email: "ahmad.fauzi@example.com",
    phone: "+62812345678",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Computer Networks",
    experience: 3,
    skills: "Cisco networking, Wireshark, Network troubleshooting, Linux administration",
    status: "active",
    courses: ["Computer Networks", "Network Security", "Network Programming"],
    schedule: [
      {
        day: "Monday",
        time: "08:00 - 10:00",
        course: "Computer Networks",
        room: "Lab 101",
      },
      {
        day: "Wednesday",
        time: "13:00 - 15:00",
        course: "Network Security",
        room: "Lab 103",
      },
    ],
    ratings: {
      studentFeedback: 4.7,
      technicalKnowledge: 4.8,
      communication: 4.5,
      reliability: 4.9,
    },
    attendance: {
      present: 28,
      absent: 0,
      late: 2,
    },
  },
  {
    id: "2",
    name: "Siti Rahayu",
    studentId: "2020573011",
    email: "siti.rahayu@example.com",
    phone: "+62812345679",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Database Systems",
    experience: 2,
    skills: "SQL, MySQL, PostgreSQL, Database design, Data modeling",
    status: "active",
    courses: ["Database Systems", "Advanced Database", "Data Warehousing"],
    schedule: [
      {
        day: "Tuesday",
        time: "10:00 - 12:00",
        course: "Database Systems",
        room: "Lab 202",
      },
      {
        day: "Thursday",
        time: "15:00 - 17:00",
        course: "Advanced Database",
        room: "Lab 204",
      },
    ],
    ratings: {
      studentFeedback: 4.5,
      technicalKnowledge: 4.6,
      communication: 4.8,
      reliability: 4.7,
    },
    attendance: {
      present: 26,
      absent: 1,
      late: 3,
    },
  },
  {
    id: "3",
    name: "Budi Santoso",
    studentId: "2020573012",
    email: "budi.santoso@example.com",
    phone: "+62812345680",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Programming",
    experience: 4,
    skills: "Java, Python, C++, Data Structures, Algorithms, Web Development",
    status: "active",
    courses: ["Programming Fundamentals", "Object-Oriented Programming", "Data Structures"],
    schedule: [
      {
        day: "Monday",
        time: "10:00 - 12:00",
        course: "Programming Fundamentals",
        room: "Lab 301",
      },
      {
        day: "Friday",
        time: "08:00 - 10:00",
        course: "Data Structures",
        room: "Lab 303",
      },
    ],
    ratings: {
      studentFeedback: 4.9,
      technicalKnowledge: 5.0,
      communication: 4.7,
      reliability: 4.8,
    },
    attendance: {
      present: 30,
      absent: 0,
      late: 0,
    },
  },
  {
    id: "4",
    name: "Dewi Lestari",
    studentId: "2020573013",
    email: "dewi.lestari@example.com",
    phone: "+62812345681",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Multimedia",
    experience: 2,
    skills: "Adobe Creative Suite, UI/UX Design, Video Editing, 3D Modeling",
    status: "probation",
    courses: ["Multimedia Design", "Digital Imaging", "Animation"],
    schedule: [
      {
        day: "Tuesday",
        time: "13:00 - 15:00",
        course: "Multimedia Design",
        room: "Lab 401",
      },
    ],
    ratings: {
      studentFeedback: 3.8,
      technicalKnowledge: 4.2,
      communication: 3.5,
      reliability: 3.0,
    },
    attendance: {
      present: 20,
      absent: 5,
      late: 5,
    },
  },
  {
    id: "5",
    name: "Eko Prasetyo",
    studentId: "2020573014",
    email: "eko.prasetyo@example.com",
    phone: "+62812345682",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Artificial Intelligence",
    experience: 3,
    skills: "Machine Learning, Deep Learning, TensorFlow, PyTorch, Computer Vision",
    status: "active",
    courses: ["Artificial Intelligence", "Machine Learning", "Deep Learning"],
    schedule: [
      {
        day: "Wednesday",
        time: "10:00 - 12:00",
        course: "Artificial Intelligence",
        room: "Lab 501",
      },
      {
        day: "Friday",
        time: "13:00 - 15:00",
        course: "Machine Learning",
        room: "Lab 503",
      },
    ],
    ratings: {
      studentFeedback: 4.6,
      technicalKnowledge: 4.9,
      communication: 4.4,
      reliability: 4.5,
    },
    attendance: {
      present: 27,
      absent: 1,
      late: 2,
    },
  },
  {
    id: "6",
    name: "Putri Handayani",
    studentId: "2020573015",
    email: "putri.handayani@example.com",
    phone: "+62812345683",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Computer Networks",
    experience: 1,
    skills: "Network configuration, TCP/IP, Routing protocols",
    status: "inactive",
    courses: ["Computer Networks"],
    schedule: [],
    ratings: {
      studentFeedback: 4.0,
      technicalKnowledge: 3.8,
      communication: 4.2,
      reliability: 3.5,
    },
    attendance: {
      present: 15,
      absent: 3,
      late: 2,
    },
  },
  {
    id: "7",
    name: "Rudi Hermawan",
    studentId: "2020573016",
    email: "rudi.hermawan@example.com",
    phone: "+62812345684",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Database Systems",
    experience: 2,
    skills: "Database administration, SQL optimization, NoSQL databases",
    status: "active",
    courses: ["Database Systems", "NoSQL Databases"],
    schedule: [
      {
        day: "Monday",
        time: "15:00 - 17:00",
        course: "Database Systems",
        room: "Lab 202",
      },
      {
        day: "Thursday",
        time: "10:00 - 12:00",
        course: "NoSQL Databases",
        room: "Lab 203",
      },
    ],
    ratings: {
      studentFeedback: 4.3,
      technicalKnowledge: 4.5,
      communication: 4.1,
      reliability: 4.4,
    },
    attendance: {
      present: 25,
      absent: 2,
      late: 3,
    },
  },
  {
    id: "8",
    name: "Nina Wati",
    studentId: "2020573017",
    email: "nina.wati@example.com",
    phone: "+62812345685",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Programming",
    experience: 1,
    skills: "Web development, JavaScript, React, Node.js",
    status: "probation",
    courses: ["Web Programming"],
    schedule: [
      {
        day: "Wednesday",
        time: "15:00 - 17:00",
        course: "Web Programming",
        room: "Lab 302",
      },
    ],
    ratings: {
      studentFeedback: 3.7,
      technicalKnowledge: 4.0,
      communication: 3.5,
      reliability: 3.2,
    },
    attendance: {
      present: 18,
      absent: 4,
      late: 8,
    },
  },
  {
    id: "9",
    name: "Hadi Wijaya",
    studentId: "2020573018",
    email: "hadi.wijaya@example.com",
    phone: "+62812345686",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Multimedia",
    experience: 3,
    skills: "Graphic design, Motion graphics, Sound editing",
    status: "active",
    courses: ["Digital Imaging", "Motion Graphics", "Sound Design"],
    schedule: [
      {
        day: "Tuesday",
        time: "08:00 - 10:00",
        course: "Digital Imaging",
        room: "Lab 402",
      },
      {
        day: "Friday",
        time: "10:00 - 12:00",
        course: "Motion Graphics",
        room: "Lab 403",
      },
    ],
    ratings: {
      studentFeedback: 4.5,
      technicalKnowledge: 4.7,
      communication: 4.6,
      reliability: 4.8,
    },
    attendance: {
      present: 29,
      absent: 1,
      late: 0,
    },
  },
  {
    id: "10",
    name: "Maya Sari",
    studentId: "2020573019",
    email: "maya.sari@example.com",
    phone: "+62812345687",
    avatar: "/placeholder.svg?height=40&width=40",
    lab: "Artificial Intelligence",
    experience: 2,
    skills: "Natural language processing, Data analysis, Python",
    status: "active",
    courses: ["Natural Language Processing", "Data Mining"],
    schedule: [
      {
        day: "Monday",
        time: "13:00 - 15:00",
        course: "Natural Language Processing",
        room: "Lab 502",
      },
      {
        day: "Thursday",
        time: "13:00 - 15:00",
        course: "Data Mining",
        room: "Lab 504",
      },
    ],
    ratings: {
      studentFeedback: 4.4,
      technicalKnowledge: 4.6,
      communication: 4.3,
      reliability: 4.5,
    },
    attendance: {
      present: 26,
      absent: 2,
      late: 2,
    },
  },
]

